- mythtv/bindings/perl/MythTV/Program.pm
- mythtv/contrib/user_jobs/mythlink.pl
Allow mythlink to use episode and season number (left padded with 0's to two digits) and Internet reference number when formatting the symlink. Works well with Plex Media Server (format: '%T/Season %ss/%T%-s%sse%ep').
> Add Season/Episode/InetRefNum support to mythlink.pl

- mythtv/bindings/python/MythTV/dataheap.py
fix for Python bindings no longer add missing 'videocategory'.'category' during method update() for Video object
https://code.mythtv.org/trac/ticket/12458
> fix as in trac #12458

- mythtv/libs/libmythtv/cardutil.h
- mythtv/libs/libmythtv/driveroption.h
A couple of C++11 constructs snuck in, causing a build failure
on GCC 4.6.  Convert these to their compatible counterparts.
> libmythtv: Fix build failure on GCC versions less than 4.8

- mythtv/programs/mythfilldatabase/xmltvparser.cpp
If this is accepted, could this be pushed down into fixes-0.27 as well?
> Fixes #12503 Prevents program categories being converted to lower-case to bring inline with categories imported over EIT

- mythtv/libs/libmyth/programinfo.cpp
- mythtv/libs/libmyth/programinfo.h
- mythtv/libs/libmythservicecontracts/services/dvrServices.h
- mythtv/programs/mythbackend/services/dvr.cpp
- mythtv/programs/mythbackend/services/dvr.h
This PR adds two functions GetSavedBookmark and SetSavedBookmark they were done largely in the style of #12090. I thought about adding the ability to pull the full markup (in fact I am not sure the other GetRecordedCutList shouldn't do this and let the user sort the types out) but this still left how best to set a bookmark without adding a more complex markup setting function.
I think this simplified version of just Get/Set bookmark adds the remaining  missing hunk to the services api for markup, no it doesn't add the metadata of #11491 but that probably should come from elsewhere.
Both functions take very similar args to #12090.
I did refactor the QueryKeyFramePosition and QueryKeyFrameDuration main function code into one function, as I was adding two more …
> Added dvr services call for setting and getting bookmark position

- mythtv/libs/libmythservicecontracts/datacontracts/videoMetadataInfo.h
- mythtv/libs/libmythservicecontracts/services/videoServices.h
- mythtv/programs/mythbackend/services/serviceUtil.cpp
Simple patch adding ChildID to the VideoMetadataInfo so that people who have multi-part videos have a way of re-assembling via the service API.
> Added ChildID to VideoService VideoMetadataInfo for Video Services API

- mythtv/libs/libmythtv/videobuffers.cpp
Corrects a mistake in the commit referenced above. In that commit a
sleep was increased from 100 microseconds to 100 milliseconds. This
proposed change reverts the sleep to the original 100 microseconds.
pull requests due to missing tickets.)
https://code.mythtv.org/trac/wiki/TicketHowTo
https://code.mythtv.org/trac/newticket
> Correction to commit: ff37862c27cc678ae201e55a5aad3af2ac3a66e3

- mythtv/libs/libmythbase/mythdirs.cpp
- mythtv/libs/libmythbase/mythdirs.h
- mythtv/libs/libmythtv/previewgeneratorqueue.cpp
- mythtv/libs/libmythui/mythuihelper.cpp
- mythtv/libs/libmythui/mythuihelper.h
- mythtv/programs/mythfrontend/main.cpp
- mythtv/programs/mythfrontend/themechooser.cpp
Create a couple of additional caching directories, and implement aging on them.  By default anything not accessed in one week is removed, and this aging is performed with mythfrontend starts and exits. (Specifically its when the MythUIHelper object is created/destroyed.) The cache directories used by this commit are all under ~/.cache and are:
1. remotecache : Existing. Copies of video screenshots from the backend. Now aged out.
2. themecache/\<themename\>-\<size\> : Existing. Now contains only theme related thumbnails. No aging.
3. thumbnails : New. Non theme related thumbnails are now stored here instead of in the themecache directories. Aged out.
4. themechooser : Location where the downloaded themes.zip is unpacked by the theme chooser. Moved here from …
> Rearrange cached files and add aging.

- mythtv/bindings/python/MythTV/_conn_mysqldb.py
Recent versions of MySQLdb sometimes pass the query as a bytearray that has been encoded using the database encoding which then causes an exception as you can't pass a bytearray to join.
> Update log_query to handle bytearray queries

- .gitignore
- mythplugins/settings.pro
- mythtv/Makefile
- mythtv/libs/libmythtv/test/test_eitfixups/test_eitfixups.pro
- mythtv/libs/libmythtv/test/test_iptvrecorder/test_iptvrecorder.pro
- mythtv/libs/libmythtv/test/test_mpegtables/test_mpegtables.pro
- mythtv/settings.pro
Clean up working directories by stashing all the compiler generated
objects in hidden subdirectories.  This patch is a combination of a
suggestion from the "Design Patterns in C++ with Qt" book and code
already in the setting.pro file.
Fixes https://code.mythtv.org/trac/ticket/13070
> Hide generated objects in subdirectories.

- mythtv/programs/mythfrontend/progdetails.cpp
This flag was added in https://github.com/MythTV/mythtv/commit/72d437001e74c57f64217de14c383e22e081a857
Signed-off-by: Ian Campbell <ijc@hellion.org.uk>
(filed as https://code.mythtv.org/trac/ticket/13316)
> Include damaged status in program details attribute list.

- mythtv/libs/libmythmetadata/metadatadownload.cpp
Since 0.27 the code requires both season and episode to be set, and setting season
to 0 is parsed to a false value. 0 is used to mean Specials by thetvdb that the previous
0.26 code understood. Other places in the code handle this correctly. Small change
to fix this.
pull requests due to missing tickets.)
https://code.mythtv.org/trac/wiki/TicketHowTo
https://code.mythtv.org/trac/newticket
> Fix thetvdb Specials

- mythtv/libs/libmythui/cecadapter.cpp
The remote control on a samsung smart TV sends a few non standard key codes over CEC. Specifically, the esc/back/return button to navigate menus.
> Extra keys for samsung smart TV remote

- mythplugins/mythmusic/mythmusic/playlist.cpp
- mythtv/libs/libmythmetadata/metaioflacvorbis.cpp
I noticed that mythmusic wasn't handling multi-disc albums correctly.
* the flacvorbis metadata handler didn't know about the `DISCNUMBER` tag so I added it (I added `TOTALTRACKS` and `TOTALDISCS` while I was there too). My goto reference for tag names is https://picard.musicbrainz.org/docs/mappings/ (all my music is tagged using Picard so this is what I've ended up with).
* once the discnumber was in the DB I noticed that the album sort wasn't handling it correctly, e.g. for a two disc album it would sort disc.track-wise as 1.1, 2.1, 1.2, 2.2, etc rather than 1.1, 1.2, ..., 2.1, 2.2. Incorporate the disc number into the album order to correct this. I believe a single CD can have at most 99 tracks so use a multiplier of 100. This means a 10 disc box set would clash with album map order …
> mythmusic fixes for multiple discs

- mythtv/bindings/python/MythTV/static.py
The Python API binding is missing several constants related to jobqueue:
89b6416b50c  78 (Robert McNamara          2011-07-03 16:49:38 -0700  79)     JOB_METADATA     = 0x0004,
ab33dd919ef  80 (John Poet                2018-03-08 16:02:25 -0700  80)     JOB_PREVIEW      = 0x0008,
I already updated:
* https://www.mythtv.org/wiki/Job_Queue
* https://www.mythtv.org/wiki/Jobqueue_table
pull …
> Python: Update JOBTYPEs

- mythtv/programs/mythfilldatabase/filldata.h
With commit 3260e981 the DataDirect grabber was removed from the
code base.
The vector dd_dups (which was only used by the DataDirect grabber)
was not removed from the Source struct at that time.  Remove it.
> Remove a lingering DataDirect grabber artifact in filldata.h

- mythtv/libs/libmythmetadata/metadatagrabber.cpp
- mythtv/programs/scripts/metadata/Movie/tmdb3.py
ttvdb and tmdb are sometimes quite slow to respond to queries, and the 60 seconds timeout is really too short. Extending it to 180s (3 minutes) solves issues for me, and allow fetching of metadata for all movies / series in my library (which are many).
I have a very fast (fiber) internet connection, so the issue is not my connection, also multiple reports on this issue can be found on the web. For some reason, slower replies of tmdb seem linked to certain movies. Meaning that some queries yield a reply in less than 60 seconds, yet consistent repeated queries for certain movies never return a result within 60 seconds.
> extend metadatagrabber timeout to 3 minutes

- mythtv/bindings/python/MythTV/ttvdb/XSLT/tvdbQuery.xsl
When performing a manual search for metadata for a video, the artwork
fetch was failing: no thumbnail was shown and no artwork was being
associated with the video. Ticket 13518 mentioned strange urls containing
"banners/_cache//banners". This commit fixes the bad urls and seems to
restore the downloading of the artwork. I don't know what led to the need
for this.
- [x ] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x ] contribution is in a branch …
> Fix incorrect artwork urls returned from ttvdb grabber

- mythtv/libs/libmythupnp/upnpcds.cpp
Returning more than requested number of elements
causes the TV to display the folder as empty.
> Fix empty UPnP Recodings folder on Samsung TV

- mythtv/programs/mythtranscode/external/replex/multiplex.cpp
- mythtv/programs/mythtranscode/external/replex/multiplex.h
- mythtv/programs/mythtranscode/external/replex/replex.cpp
- mythtv/programs/mythtranscode/mpeg2fix.cpp
Fix for #244 which was originally https://code.mythtv.org/trac/ticket/12602
Explanation of the patch:
* multiplex.h:
the mx multiplex structure gets a new "int error", the error count.
write_out_packs and finish_mpg now return int, the error count (so 0 = success)
currently unused: callers test the error count instead
* multiplex.c:
if write() fails, increment error count
log only first 10 failures so we don't flood syslog and cause it to drop messages
if close() fails, increment error count
* mpeg2fix.cpp:
copy error count to static variable and pass it to pthread_exit
capture error count in pthread_join and log/fail if non-zero
This all causes mythtv to keep the original recording if disk fills during transcode, instead of truncating the recording.  Of course user will need to go free …
> mythtranscode: Fix #244 by detecting write errors

- mythplugins/configure
- mythplugins/mythmusic/mythmusic/editmetadata.cpp
- mythplugins/mythmusic/mythmusic/editmetadata.h
If qtwebkit (and therefore mythuiwebbrowser) are not available then omit the menu items relating to searching for artwork on the internet.
Fixes #328 (or at least, worksaround I suppose)
---
> Make use of mythuiwebbrowser.h bits in mythmusic optional

- mythtv/libs/libmythtv/subtitlereader.cpp
Karaoke-style Sub-Station Alpha (SSA) subtitles with decorative animations (e.g.: bouncing ball position) do not render correctly in MythFrontend due to an arbitrary(?) subtitle-buffers-count limit of 40.  Increasing this amount, and testing on various sources leads to a better value (of 175) which works for more different of subtitle karaoke-animation styles.
Code is branched off fixes/31
Issue Ref: https://github.com/MythTV/mythtv/issues/355
> Increase cut-off for subtitle buffer clear, too small for SSA karaoke

- mythtv/programs/scripts/hardwareprofile/distros/mythtv_data/data_mythtv.py
With Python 3.8 a syntax warning is now generated during
compilation when one is using 'is' or 'is not' to compare
to certain types of literals, as such use is not assured
to work properly to work with all interpreters.  This
syntax warning was a result of issue bpo-34850.
Fixes #370
> Compare literals using '!=' not 'is not'

- mythtv/programs/mythfrontend/videodlg.cpp
Results in warning "Qt: QString::arg: 1 argument(s) missing in %2.%3"
and failure to retrieve coverart files
Fixes #378
> Fix QString arguments when searching for remote coverart files

- mythplugins/mythgame/mythgame/scripts/giantbomb.py
- mythplugins/mythgame/mythgame/scripts/giantbomb/XSLT/giantbombGame.xsl
- mythplugins/mythgame/mythgame/scripts/giantbomb/XSLT/giantbombQuery.xsl
- mythplugins/mythgame/mythgame/scripts/giantbomb/giantbomb_api.py
- mythplugins/mythgame/mythgame/scripts/giantbomb/giantbomb_exceptions.py
A huge thanks to @rcrdnalor for updating this to Python 3.
The motivation behind my change is to reduce the load on the GiantBomb servers by going directly to their HTTPS end point rather then making them 301 redirect us each time.
I've also updated the links to documentation throughout the code which were missing (lxml) or redirecting back to home pages (GiantBomb API).
I didn't update the large XML reply examples as I didn't want to flood the diff but happy to do that.
I wasn't sure if changing the namespace of the XSLT transforms in mythplugins/mythgame/mythgame/scripts/giantbomb/XSLT was appropriate. It didn't seem to be used outside of the giantbomb scripts but happy to revert if they should remain as http which would be similar to how w3.org namespaces remain at http.
> Use GiantBomb HTTPS API

- mythtv/libs/libmyth/audio/audiooutputca.cpp
- mythtv/libs/libmythtv/libmythtv.pro
- mythtv/libs/libmythui/devices/AppleRemoteListener.cpp
- mythtv/programs/mythfrontend/globalsettings.h
Fixes to get mythtv-master compiling with Qt6 on macOS
> MacOS Qt6 updates

- mythtv/libs/libmythupnp/httprequest.cpp
The lines were commented out by 9846f8f6e3eddcbf1e5d74c50d5f994bbe162a66 in 2014.
No functional change.
@linuxdude42 requested this be separated from https://github.com/MythTV/mythtv/pull/442
> httprequest.cpp: remove unused USE_SETSOCKOPT code

- mythtv/programs/mythfilldatabase/filldata.cpp
- mythtv/programs/mythfilldatabase/filldata.h
This pull request is related to issue #412
> Performance improvements for mythtv-setup "Fetch channels from listing source"

- .github/workflows/buildmaster.yml
ccache does not appear to work on the macOS actions.  I will attempt to enable and verify it on the macOS workflows.
> GitHub Actions (macOS): persist ccache's cache between runs

- mythtv/libs/libmythtv/mythplayeroverlayui.cpp
- mythtv/libs/libmythtv/playercontext.cpp
- mythtv/libs/libmythtv/playercontext.h
- mythtv/themes/MythCenter-wide/osd.xml
- mythtv/themes/MythCenter/osd.xml
- mythtv/themes/Terra/osd.xml
This replaces #127 which can now be closed.
This adds "recordedtime" of the recording which themes can add to the OSD.  This is handy for delayed live events or when you are just curious what time the show aired.  The shipped Terra, MythCenter and MythCenter-wide are updated as examples.  I didn't touch default since I am not sure how to test it.  I currently use this with Mythbuntu on fixes/31 via 17d4994dd28c396f4ea7b12d4fd58d3d1446881d and a3fac2f60e6901f853ee82126dc00ba87fea71b9.
- Setup option to toggle this clock per user preference.  If the xml can't be conditional then the code could return an empty string to display nothing.
> Recorded time for OSD

- mythplugins/settings.pro
- mythtv/settings.pro
ARCH_POWERPC is not set anymore, neither is any TARGET_ARCH_...
This should have no functional change.  Also, the purported reason is probably
no longer valid.
ARCH_POWERPC is now ARCH_PPC(64).
> settings.pro: remove 17 year old stale ARCH conditions

- mythtv/libs/libmythtv/visualisations/goom/zoom_filter_xmmx.cpp
and remove use of ARCH_...
MMX is a CONFIG_DEFINES in configure
https://github.com/MythTV/mythtv/blob/8cbe83862ccf2c467758e87c7d9d100176daf7c6/mythtv/configure#L7899-L7904
mythconfig.h always has ARCH_... defined.
Modified from commit in https://github.com/MythTV/mythtv/pull/470
> goom: re-enable zoom_filter_xmmx.cpp for x86_32

- mythtv/libs/libmythtv/recorders/dvbdev/dvbci.cpp
build: Fix build under FreeBSD 13.0
Error was: 
recorders/dvbdev/dvbci.cpp:265:38: error: implicit instantiation of undefined template 'std::__1::array<unsigned char, 2048>'
std::array<uint8_t,MAX_TPDU_SIZE>  m_data {0};
> Fix build of dvbci.cpp

- mythtv/libs/libmythtv/mythdeinterlacer.cpp
Was part of https://github.com/MythTV/mythtv/pull/470
I also added [std::thread::hardware_concurrency()](https://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency) as a hint for the maximum number of threads.
> Deinterlacer: Clamp threads

- mythtv/libs/libmythfreesurround/el_processor.cpp
- mythtv/libs/libmythfreesurround/el_processor.h
This was originally part of https://github.com/MythTV/mythtv/pull/416 .  However, it stands on its own, so I have split it off.
This is motivated by https://github.com/MythTV/mythtv/issues/428 enable use of system FFmpeg.
Note: for testing most of the changes, `./configure --disable-fftw3`
> libmythfreesuround cleanup (remove internal FFmpeg header fft.h)

- mythtv/programs/mythfrontend/playbackbox.cpp
The transcoding profiles menu needs to be shown when the transcoding job
is not running.
With commit bf15fbee54 the logic was inverted accidently.
> Show transcoding profiles menu when job is _not_ running

- mythtv/libs/libmythbase/mythdate.cpp
- mythtv/programs/mythcommflag/CommDetector2.cpp
@linuxdude42 You missed some in https://github.com/MythTV/mythtv/commit/65b9c73adacabe38877c3e18af5d4a0545799c16
See commit messages for details.
> fixup MythDate::formatTime() calls and doxygen

- mythtv/libs/libmyth/audio/audioconvert.cpp
- mythtv/libs/libmyth/audio/audiooutpututil.cpp
- mythtv/libs/libmyth/audio/audiooutpututil.h
- mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
Was in https://github.com/MythTV/mythtv/pull/470
x86_64 requires SSE2, so just return true for the SSE2 check in that case.
The new function names better represent what they do.
> Rename/minor changes to audio functions using SSE2

- mythtv/libs/libmythbase/signalhandling.cpp
- mythtv/libs/libmythbase/signalhandling.h
- mythtv/programs/mythavtest/main.cpp
- mythtv/programs/mythbackend/main.cpp
- mythtv/programs/mythccextractor/main.cpp
- mythtv/programs/mythcommflag/main.cpp
- mythtv/programs/mythfilldatabase/main.cpp
- mythtv/programs/mythfrontend/main.cpp
- mythtv/programs/mythjobqueue/main.cpp
- mythtv/programs/mythlcdserver/main.cpp
- mythtv/programs/mythmediaserver/main.cpp
- mythtv/programs/mythmetadatalookup/main.cpp
- mythtv/programs/mythpreviewgen/main.cpp
- mythtv/programs/mythscreenwizard/main.cpp
- mythtv/programs/mythshutdown/main.cpp
- mythtv/programs/mythtranscode/main.cpp
- mythtv/programs/mythtv-setup/main.cpp
- mythtv/programs/mythutil/main.cpp
- mythtv/programs/mythwelcome/main.cpp
The only functional change is mythavtest and mythscreenwizard now use the logSigHup() signal handler, like the rest of the programs, instead of just ignoring it.
SIGHUP is hangup, which is raised when the terminal that launched it closes (or the session logs out, if I understand correctly), and by default terminates the application https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/signal.h.html .
By ignoring SIGHUP the application outlives the terminal that launched it, which makes more sense as a default when the program was launched as a background process with `&`.
logSigHup() calls FileLogger::reopen for each FileLogger, which presumably closes the logging to the terminal and fails to reopen it.
https://github.com/MythTV/mythtv/blob/1a9204f41e09c3a4652e1eec058d820c184a29f2/myth …
> de-duplicate signal handler code

- mythtv/libs/libmythtv/decoders/avformatdecoder.h
- mythtv/libs/libmythtv/mythplayer.h
Doxygen doesn't list uses of MACROs.
> make FlagIsSet() a protected function instead of a MACRO

- mythtv/bindings/perl/MythTV/Program.pm
Fix videoproperties which were wrong after the schema change to 1362 in commit e79b8fc.
Add additional videoprop flags.
> Perl bindings: Fix videoproperties after schema change to 1362, add additional videoprop flags

- mythtv/libs/libmyth/audio/audioconvert.cpp
- mythtv/libs/libmyth/audio/audiooutpututil.cpp
Was part of https://github.com/MythTV/mythtv/pull/430
The QtEndian conversion is not complete, but this was sufficient to remove libmythbase/bswap.h.
`git grep -nE BIGENDIAN -- :^*/external/**` still shows a few files.
> Minor cleanup to audio code

- mythtv/libs/libmythbase/mythdate.cpp
Fixes [PR535](https://github.com/MythTV/mythtv/issues/535) on fixes/32
> Fixes/32: Add missing include <array> to mythdate

- mythtv/libs/libmythbase/platforms/mythpowerdbus.cpp
- mythtv/libs/libmythtv/Bluray/mythbdoverlay.cpp
- mythtv/libs/libmythtv/DVD/mythdvdbuffer.cpp
- mythtv/libs/libmythtv/mythvideoprofile.cpp
- mythtv/libs/libmythui/mythdisplay.cpp
std::clamp() is used elsewhere in the codebase and, in my opinion, has a better parameter ordering than qBound.  (std::clamp(val, min, max) vs. qBound(min, val, max))
> replace qBound() with C++17 std::clamp()

- mythtv/libs/libmyth/audio/audiooutputca.cpp
- mythtv/libs/libmyth/audio/audiooutputsettings.cpp
- Fixed audio device detection
- Fixed Surround Sound channel capability detection (5.1+ speakers)
- Fixed memory corruption and leaks
- [x ] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [ x] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [x ] code compiles successfully without errors
- [ x] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [x ] commits are logically …
> mythfrontend audio fixes for macOS

- mythplugins/mythmusic/mythmusic/bumpscope.cpp
- mythplugins/mythmusic/mythmusic/decoderhandler.cpp
- mythplugins/mythmusic/mythmusic/musiccommon.cpp
- mythplugins/mythmusic/mythmusic/vorbisencoder.cpp
- mythtv/libs/libmythbase/bonjourregister.cpp
- mythtv/libs/libmythbase/http/mythwebsocket.cpp
- mythtv/libs/libmythbase/mythcorecontext.cpp
- mythtv/libs/libmythbase/mythdbcon.cpp
- mythtv/libs/libmythbase/mythrandom.cpp
- mythtv/libs/libmythbase/mythrandom.h
- mythtv/libs/libmythfreemheg/Programs.cpp
- mythtv/libs/libmythtv/AirPlay/mythairplayserver.cpp
- mythtv/libs/libmythtv/eitscanner.cpp
- mythtv/libs/libmythtv/eitscanner.h
- mythtv/libs/libmythtv/recorders/rtp/packetbuffer.cpp
- mythtv/libs/libmythtv/recorders/rtp/packetbuffer.h
- mythtv/libs/libmythtv/test/test_copyframes/test_copyframes.cpp
- mythtv/libs/libmythtv/tv_rec.cpp
- mythtv/libs/libmythui/mythuitype.cpp
- mythtv/libs/libmythupnp/mmulticastsocketdevice.cpp
- mythtv/libs/libmythupnp/ssdp.cpp
- mythtv/libs/libmythupnp/upnptasknotify.cpp
- mythtv/libs/libmythupnp/upnptasksearch.cpp
- mythtv/programs/mythbackend/mainserver.cpp
- mythtv/programs/mythfrontend/playbackbox.cpp
- mythtv/programs/mythfrontend/videodlg.cpp
This also removes the conditional compilation due to the Qt random number generator functions added in 5.10.
> Use C++ <random> instead of Qt or POSIX

- mythtv/libs/libmythbase/mythdate.cpp
- mythtv/libs/libmythbase/mythdate.h
This is redone without the inlining from https://github.com/MythTV/mythtv/pull/466
> mythdate: match type with Qt, preventing potential Y2106 bug

- mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
- mythtv/libs/libmythtv/decoders/avformatdecoder.h
and move it to the only function using it.
This was originally part of https://github.com/MythTV/mythtv/pull/416
> avformatdecoder.cpp: precompute parity LUT

- mythtv/programs/mythtranscode/mpeg2fix.cpp
- mythtv/programs/mythtranscode/mpeg2fix.h
This was originally part of https://github.com/MythTV/mythtv/pull/416
> precompute inverse zigzag scan LUT

- mythtv/programs/mythfrontend/playbackbox.cpp
(Also fixes the problem, when determining which episode to display, of air
date taking priority over series and episode)
Before this change, the watch list used a complex ordering that was
designed to help users keep up to date with many series simultaneosly,
ensuring that they didn't get behind with some. It's cleverly designed,
but seems very specific to the author's particular viewing habits. It
doesn't account well for shows that you really don't want to watch just
now, but you think you might one day. Nor does it account for a wish to
wait for a whole series before binging.
This commit simplifies the design, taking the view that mostly the user
will want to continue with series that they've recently viewed, or one to
which a new recording has recently been added. The new ordering …
> Base watch list ordering on series most recently warched or recorded

- mythtv/libs/libmythui/mythedid.cpp
found by valgrind while investigating segmentation faults that
occured randomly on startup of mythfrontend.
There are only 4 descriptors in the EDID data structure.
By incorrectly looping 5 times in MythEDID::ParseBaseBlock(),
an offset of 126 is passed to ParseDisplayDescriptor() or
ParseDetailedTimingDescriptor() which will then read past
the end of the 128 byte EDID data structure.
This appears to have always been wrong since it was added in
53d170221983764ae108939cbdb0bcbfc48b6114 .
> MythEDID: fix out of bounds memory access

- mythtv/programs/mythfrontend/exitprompt.cpp
discvered by valgrind:
```
2022-06-28 01:34:29.544115 I [25872/25872] CoreContext exitprompt.cpp:24:ExitPrompter  Created ExitPrompter
==25872== Invalid write of size 8
==25872==    at 0x5C38AC1: MythDialogBox::SetReturnEvent(QObject*, QString const&) (mythdialogbox.cpp:304)
==25872==    by 0x2A852C: ExitPrompter::~ExitPrompter() (exitprompt.cpp:31)
==25872==    by 0x2A888C: ExitPrompter::~ExitPrompter() (exitprompt.cpp:36)
==25872==    by 0xA4B61B2: QObject::event(QEvent*) (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.3)
==25872==    by 0x63BB712: QApplicationPrivate::notify_helper(QObject*, QEvent*) (in /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.3)
==25872==    by 0xA488E29: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.3) …
```
> mythfrontend/exitprompt.cpp: fix use after free

- mythtv/libs/libmyth/mediamonitor-unix.cpp
- mythtv/libs/libmyth/mediamonitor-unix.h
UDisks is long time deprecated and not available in modern Linux
distributions anymore.
It was replaced by UDisks2 which is now provided by the storaged.org
project and linked from freedesktop.org.
See https://udisks.freedesktop.org/ and
http://storaged.org/doc/udisks2-api/latest/ for details.
When monitoring is enabled in the frontend:
Setup -> General ->  Monitor Devices
a 'MythMediaDevice' is added for every removeable device.
Refs https://github.com/MythTV/mythtv/issues/605
> MythMediaMonitor: Replace UDisks with UDisks2

- .github/workflows/buildmaster.yml
The macOS-10.15 environment is deprecated and will be removed on August 30th, 2022.
> GitHub Actions: update macOS versions

- mythtv/libs/libmythtv/bitreader.h
If bits == 0, which should never occur, we want the top 0 bits.
Return 0, as would be expected from shifting in 64 `0` bits.
Also, mask_upper(0) returns 0, which would clear all the bits anyways.
@linuxdude42 This is the correct return value for an input of 0.
> bitreader.h: get_upper_bits() make undefined behavior protection consistent

- mythtv/libs/libmythbase/unzip2.h
- mythtv/libs/libmythbase/unziputil.cpp
unzip2.(h|cpp) does not use any zlib symbols, only unziputil.cpp does.
> unziputils: move zlib include to proper file

- .github/workflows/buildmaster.yml
This reverts commit 1d4074607fe90b3183bdc287151cf11ea5a8d94a.
My understanding of the caches was incorrect.  The caches are immutable, see https://github.com/actions/cache/blob/main/workarounds.md#update-a-cache
To keep the ccache up to date, restore the previous behavior of using a unique key for each run.  This is the accepted method to update a cache.
---
@stuarta This needs to be reverted to keep the cache up to date.  My reasoning was sound, but incorrect, since caches are immutable.
> Revert "GitHub Actions: overwrite prior cache instead of rotating"

- mythtv/libs/libmythtv/bitreader.h
- mythtv/libs/libmythtv/mpeg/HEVCParser.cpp
- mythtv/libs/libmythtv/test/test_bitreader/test_bitreader.cpp
- mythtv/libs/libmythtv/test/test_bitreader/test_bitreader.h
@jpoet The first three commits are fixes, then more unit tests, and some minor tidying up.
skip_bits() was broken for non aligned byte skips when the cache had data in it.  The new unit tests satisfy me that it works correctly now, but testing would be appreciated.
> Fix BitReader

- mythtv/libs/libmythtv/mpeg/HEVCParser.cpp
This caused the bitstream to become misaligned for the satelite channel FashionTV UHD, which then caused the framerate to become an incorrect value.
Fixes https://github.com/MythTV/mythtv/issues/650
---
I could only test with two HEVC samples, so further testing would be greatly appreciated.
> HEVCParser: fix parsing of st_ref_pic_set( stRpsIdx )

- mythtv/programs/mythfrontend/playbackbox.cpp
After a metadata Search within the 'Edit Recording Metadata'
screen, the subtitle value is mistakenly written to the Description
field. Then that value is usually immediately overwritten by the
real description value.
This code change fixes the problem by properly
writing to the Subtitle field.
Resolves #667
> Set Subtitle in Change Recording Metadata Search

- mythtv/programs/mythfrontend/gallerytransitions.cpp
- mythtv/programs/mythfrontend/galleryviews.cpp
Also, convert "uniform" random floating point to uniform random integers, due to the issues with random floating point implementations.
> Replace QRandomGenerator with MythRandom

- mythtv/programs/scripts/metadata/Television/tvmaze.py
The tool **pylint** reported several unnecessary includes in tvmaze.py. These have been removed to make the script run a little bit faster.
Refs: #654
> Remove unnecessary python imports in tvmaze.py

- mythtv/bindings/python/tvmaze/show.py
- mythtv/programs/scripts/metadata/Television/tvmaze.py
The script tvmaze/show.py had a line which retrieved the episode duration from the metadata provider, but then assigned it to **num_episodes**, which makes no sense. There is no code looking for **num_episodes**, but there is code looking for **runtime**, so the line has been fixed to assign to **runtime**.
Using the TVmaze service for metadata lookup, there are rare cases where the 'runtime' field is empty, but 'averageRuntime' is not. This happened when looking up metadata for a TV show called "Everything's Trash". Note that the database entry for this show was subsequently updated to include the missing 'runtime' field. But on the night it was recorded, and for several days later, that field was null.
Here's an excerpt of the original metadata for "Everything's Trash":
"id":60518, …
> Fix setting of TvMaze show runtime

- mythtv/programs/scripts/metadata/Television/tvmaze.py
In rare cases, the TvMaze database provides null **timestamp** or **runtime** data fields. To make the metadata retrieval script more fault tolerant, null checks have been added for these values.
When the timestamp field is null, don't use it to generate a datetime to use in a search for a matching episode.
When the runtime duration field is null, the delta size is now set to zero minutes. The code which looks for an episode match has been updated to separate "on time" recordings from "a little late" recordings to accommodate the possible delta size of zero.
Refs: #654
> Handle null timestamp or runtime fields in TvMaze data

- mythplugins/mythmusic/mythmusic/mainvisual.cpp
- mythplugins/mythmusic/mythmusic/visualize.cpp
- mythplugins/mythmusic/mythmusic/visualize.h
Hello,
I always loved StereoScope of MythMusic because I like to see what the sound looks like.  But I started thinking: what does this whole song look like?  Loud or soft?  Does it change much?  When will changes happen?
Here is a new "WaveForm" visualization for MythMusic.  It is StereoScope in front of a "picture" of the current track showing peak-to-peak and RMS over time.  The high resolution image is drawn in real-time the first time a track is played and cached to $HOME/.mythtv/MythMusic/WaveForm/.  This costs < 50 KBytes per track.  All replays can now see the future of the song as the progress line moves across the wave form.
Radio streams reuse just one file to show the last 1 minute of sound.
This works for me on fixes/32.  Other ideas maybe not worth the effort:
* A separate …
> MythMusic: WaveForm visualization of whole track

- mythtv/programs/mythfrontend/globalsettings.cpp
- mythtv/programs/mythfrontend/manualschedule.cpp
- mythtv/programs/mythfrontend/manualschedule.h
When a user is entering a number of Manual Record rules in a row, it would be nice if the previously used channel was remembered and used as the default for the current rule. For example, if you wanted to enter rules to record Chicago Med, Chicago Fire, and Chicago P.D., which are all on the same channel, it would save time on the second and third rules, to default to the common channel.
To implement this, when a Manual Record rule is entered, store the channel number such that it can be set as the default channel for the next Manual Record rule.
Fixes #655
> Default to last channel used in Manual Record rule

- mythtv/programs/mythbackend/scheduler.cpp
Fix the logic that sends the REC_PENDING event.
- REC_PENDING event is sent always before the REC_STARTED.
- REC_PENDING event is sent at 120, 90, 60 and 30 seconds before the start of the recording.
- Start of the recording is the scheduled program start time plus the RecordPreRoll setting value.
- When a recording is scheduled to start recording immediately then there is
one REC_PENDING event with 0 seconds immediately followed by the REC_STARTED event.
- The setting WakeUpThreshold specifies how early the slave backends are signaled to start
before the recording is started. This setting is used as configured, but now with a minimum
value of RecordPreRoll plus 120 seconds so that there is always time for the REC_PENDING events.
> Send REC_PENDING event before recording starts

- mythplugins/configure
Per analysis of Roland Ernst, mythnetvision is using it's own oauth implementation.  Remove the dependency check in the mythplugins configure script for an external library
Fixes: #713
> Remove the check for the oauth library for mythnetvision

- mythtv/libs/libmyth/audio/audiooutputca.cpp
- mythtv/libs/libmythbase/platforms/mythpowerosx.cpp
- mythtv/libs/libmythui/devices/AppleRemote.cpp
- mythtv/libs/libmythui/platforms/mythutilscocoa.mm
- Fixes regression cause by early depreication of contants by Apple in 11.5.7.
- Initial fix for macOS 12 introduced in commit 3787583
> OSX: Handle constants deprecated for 11.7 (master)

- mythtv/libs/libmyth/mediamonitor-unix.cpp
Checking for mount points is not reliable to determine if a block device is an optical drive. This commit uses the 'MediaCompatibility' property of the 'org.freedesktop.UDisks2.Drive' DBUS interface to check if the drive supports optical media.
Also changes the function name in the log messages to match the function they are called from.
- [x ] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x ] contribution is in a branch rebased against …
> Fix detection of optical drives

- mythtv/libs/libmythtv/channelscan/channelscanner.cpp
- mythtv/libs/libmythtv/channelscan/channelscanner.h
- mythtv/libs/libmythtv/channelscan/channelscanner_gui.cpp
- mythtv/libs/libmythtv/channelscan/hdhrchannelfetcher.cpp
- mythtv/libs/libmythtv/channelscan/hdhrchannelfetcher.h
- mythtv/libs/libmythtv/channelscan/scanwizardconfig.cpp
- mythtv/libs/libmythtv/channelscan/scanwizardconfig.h
- mythtv/libs/libmythtv/libmythtv.pro
- mythtv/libs/libmythtv/scanwizard.cpp
Add the option "HDHomeRun Channel Import" to get the channel list directly from the HDHomeRun. The HDHomeRun does a channel scan all by itself and the list of channels can now be read by mythtv-setup. Also the http url for each channel is read and stored in the database although this is not yet used in MythTV.
There is enough information read from the HDHomeRun to fill database tables channel and dtv_multiplex so that recording can be done with libhdhomerun. This feature has only been tested in The Netherlands and it is expected that it works with all European DVB-T/T2 and DVB-C signals. Support for reading USA/ATSC channel lists is to be added. The actual code is shamelessly copied from the channel import for the VBox and adapted where needed.
Please …
> HDHomeRun Channel Import

- mythtv/libs/libmythtv/v4l2util.cpp
- mythtv/libs/libmythtv/videosource.cpp
Fix a defect in mythtv-setup found by Peter when creating the WebApp configuration utility.
> Show "Input name" field only for analog inputs

- mythtv/libs/libmythtv/channelscan/iptvchannelfetcher.cpp
- mythtv/libs/libmythtv/tv_rec.cpp
- mythtv/libs/libmythtv/videosource.cpp
Allow IPTV (FREEBOX) tuning even when DVB tuning data for transport stream interfaces such as transport id is available. A HDHomeRun video source can be populated from an XML file with the "HDHomeRun Channel Import" function.
This loads the tuning data for the libhdhomerun interface but also an URL that can be used for HTTP streaming.
Recording HDHomeRun channels with HTTP streaming can be done by creating an IPTV (FREEBOX) capture card and connecting that capture card to the video source already populated by the HDHomeRun capture card.
The HDHomeRun capture card can then be disconnected from that video source to insure only HTTP streaming is used. Note that HDHomeRun HTTP streaming does not pass EIT data.
Please review the checklist below to ensure …
> Allow IPTV tuning from HDHomeRun video source

- mythtv/libs/libmythui/mythdisplay.cpp
- mythtv/libs/libmythui/mythuiscreenbounds.cpp
- mythtv/libs/libmythui/mythuiscreenbounds.h
- mythtv/programs/mythfrontend/globalsettings.cpp
Add a "Force Full Screen" checkbox option in Setup / Appearance/ Theme/Screen settings.
This makes it possible to go from windowed mode to full screen mode and vice versa The current method to go to full screen mode is to make all four numbers that comprise the GUI dimensions (X-offset, Y-offset, X-size and Y-size) zero; to go back to window mode these four numbers have to be entered again. The new "Force Full Screen" setting overrides the existing "GUI dimension" and "Use window border" settings but it does not change these settings. This makes it possible to go from windowed mode to full screen mode and vice versa using only a single checkbox.
> Force Full Screen option for GUI and playback

- mythtv/bindings/python/MythTV/__init__.py
- mythtv/bindings/python/MythTV/dataheap.py
- mythtv/bindings/python/MythTV/static.py
Python Bindings allow to export and import metadata providing an easy way to move recordings to the 'Videos' storagegroup.
This feature provides also an export to xml, which can be used to generate 'mxml' files on the fly.
The commits in this pull request make the import/export feature of recordings and videos consistent.
Additionally, it implements a metadata-grabber that runs on given inetref, providing exact and unique metadata data.
For details about the metadata, see
https://www.mythtv.org/wiki/MythTV_Universal_Metadata_Format
> Fix Pythons import/export of metadata

- mythplugins/configure
If the plugin MythNetVision is built together with MythTV, configure tries to determine the preliminary path of the Python Bindings.
Python3.10 deprecates the 'distutils' package, and python3.12 will remove this package, hence we need another solution to provide the correct paths to the MythTV Python libs.
Fixes MythTV#437
> Python: Remove deprecated `distutils` package.

- mythtv/libs/libmythmetadata/metadatafactory.cpp
To improve the accuracy of GuessLookupType(), the Recording Type is now factored in. If the recording type is Daily, or Weekly, then it's probably a television show.
Refs #656
- [ x] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x ] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [x ] code compiles successfully without errors
- [x ] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [x ] documentation added/updated/removed where necessary
- [x ] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)
> Use Recording Type in GuessLookupType

- mythtv/libs/libmythbase/mythcommandlineparser.cpp
Just a small PR - I read the coding standards and nothing seems at odds with it.
**Desription of change:**
This reformats sligitly the output of --help in libmyth-base by adding a two space prefix for options, and adds new lines around the different help sections.
At least with ubuntu packages help2man is used to generate the man pages, and this changes the unformatted look to normal man pages.
> Reformat the --help slightly so it conforms to GNU standard.

- mythplugins/mythmusic/mythmusic/visualize.cpp
- mythplugins/mythmusic/mythmusic/visualize.h
as the white was too bright.  Add 5 second gap to radio streams.
Also eliminate all #defines by moving the settings to class members.  Few other code cleanups that change no functionality.
> MythMusic: add percent indicator to WaveForm and shrink and dim the font

- mythplugins/mythmusic/mythmusic/visualizerview.cpp
- mythplugins/mythmusic/mythmusic/visualizerview.h
- mythplugins/mythmusic/theme/default-wide/music-base.xml
- mythplugins/mythmusic/theme/default-wide/music-ui.xml
- mythplugins/mythmusic/theme/default/music-base.xml
- mythplugins/mythmusic/theme/default/music-ui.xml
- mythtv/themes/MythCenter-wide/music-base.xml
- mythtv/themes/MythCenter-wide/music-ui.xml
and let another i key press show track details and let common widgets work so theme can show for example progress bar and time.
Fixes #780, fixes #781, enhances #785, #786.
Highly recommend custom trackinfo_popup of themes add progressbar and time to assist seeking since FFWD/REW work as expected in #785.  This is provided here in the shipped defaults and MythCenter-wide.  We also add year and track number which is nice to know when skipping to next or previous track.
The XML tweaks to time and playlisttime are for #786, done here in one place to avoid conflicts.  Ideally both should be merged near the same time.
> MythMusic: let music controls work during trackinfo popup

- mythplugins/mythmusic/mythmusic/avfdecoder.cpp
- mythplugins/mythmusic/mythmusic/mainvisual.cpp
> MythMusic: fix REW/FFWD to seek quickly

- mythplugins/mythmusic/mythmusic/musiccommon.cpp
Fixes #787 by limiting rewind to 00:01.  We can't hear that first second again, but should be close enough.  You can always NEXTTRACK / PREVTRACK to hear that first second again.  I was unable to find a way to get a seek to 00:00.  If you do, then your fix could replace mine.
> MythMusic: Fix rewinds under 00:05 by stopping at 00:01

- mythplugins/mythmusic/mythmusic/visualize.cpp
- mythplugins/mythmusic/mythmusic/visualize.h
This applies the lessons learned in Spectrogram to the original Spectrum and Squares, greatly improving them:
* FFT of complete signal
* same FFT: 16384 bins, decaying window, peak of bins
* same Mel Scale replacing log scale (much improved resolution in low frequencies, distributes the sound better across the whole screen)
* upgrade to 128 bars for better resolution
> MythMusic: Improve Spectrum and Squares

- mythplugins/mythmusic/mythmusic/musiccommon.cpp
- mythplugins/mythmusic/mythmusic/musicplayer.cpp
- mythplugins/mythmusic/mythmusic/musicplayer.h
- mythplugins/mythmusic/mythmusic/playlist.cpp
- mythplugins/mythmusic/mythmusic/playlist.h
- mythplugins/mythmusic/mythmusic/playlisteditorview.cpp
- mythplugins/mythmusic/mythmusic/searchview.cpp
- mythplugins/mythmusic/mythmusic/searchview.h
- mythplugins/mythmusic/theme/default-wide/music-base.xml
- mythplugins/mythmusic/theme/default-wide/music-ui.xml
- mythplugins/mythmusic/theme/default/music-base.xml
- mythplugins/mythmusic/theme/default/music-ui.xml
- mythtv/themes/MythCenter-wide/music-base.xml
- mythtv/themes/MythCenter-wide/music-ui.xml
ref: https://forum.mythtv.org/viewtopic.php?p=25164#p25164
Spontaneous listeners want to just play an album or song now and care less about any playlist.  This adds a simple "Play Now" to the menus which is identical to "Add Tracks" except that it immediately starts playing the additions.  When "Play Now" is preferred (a new toggle), selecting a single track adds it and plays it now, rather than just adding it.
This required moving previously added tracks to the end so that adding an album gets all tracks even if you played some of them earlier.
Possible documentation is now at the top of https://www.mythtv.org/wiki/Talk:MythMusic to be cut-n-pasted to the manual when this gets to production.
> MythMusic: "Play Now" any tracks from the music browsers

- mythplugins/mythmusic/mythmusic/avfdecoder.cpp
- mythplugins/mythmusic/mythmusic/avfdecoder.h
- mythplugins/mythmusic/mythmusic/musicplayer.cpp
Fixes #790 by parsing the changed metadata string and accepting it only if title/artist/album changed.
The LOG of raw data string and its parse is moved to DEBUG level so that stations repeating the same StreamTitle in a changing string don't spam an INFO log.  Actual changes to StreamTitle are still logged to INFO as before only at first detection of the change.
> MythMusic: handle streams that repeat same metadata in changing strings

- mythplugins/mythmusic/mythmusic/musiccommon.cpp
- mythplugins/mythmusic/mythmusic/musiccommon.h
- mythplugins/mythmusic/theme/default-wide/music-base.xml
- mythplugins/mythmusic/theme/default-wide/music-ui.xml
- mythtv/themes/MythCenter-wide/music-ui.xml
Improve #786 by providing the three time components to XML theme templates.
Like the current "playlistplayedtime" and "playlisttotaltime" that are available to XML templates, this adds the components of "time":
* playedtime -- MM:SS or H:MM:SS
* totaltime -- MM:SS or H:MM:SS
* trackspeed -- empty for normal speed or 0.95, 1.05 and so on for abnormal playback speeds
This allows themers to format these separately if they wish.  Trackspeed is an empty string until modified by speed changes (W/X keys).  Documentation is updated at https://www.mythtv.org/wiki/Music-ui.xml#Generic_Attributes_Used_in_most_windows
> MythMusic: Provide play time components to templates

- mythtv/programs/mythfrontend/scheduleeditor.cpp
This commit uses 'QCoreApplication::translate' to translate the entries of the schedule filter list as this allows to pass a translation context which is needed to find the translations of these entries.
- [x ] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x ] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [ x] code compiles successfully without errors
- [x ] code follows the [MythTV Coding …
> Fix translation of schedule filter entries

- mythplugins/mythmusic/mythmusic/visualize.cpp
- mythplugins/mythmusic/mythmusic/visualize.h
- mythplugins/mythmusic/mythmusic/visualizerview.cpp
Fix #766 by calling the visualizer's handleKeyPress from visualizerview's keyPressEvent.
SELECT key now takes action in 4 visualizers:
AlbumArt: cycles through available covers
WaveForm: toggles time and resolution text overlay
Spectrogram: cycles color graphs for either or both channels, saving this preference to the database
Spectrum: toggles note and frequency text overlay
> MythMusic: fix handleKeyPress of visualizers

- mythtv/external/FFmpeg/configure
With the introduction of Xcode 15, Apple has moved to a new linker and introduced the "-ld_classic" linker flag as a work around. Without this flag, FFMPEG fails to compile on systems with Xcode 15 (i.e. Sonoma).
This workaround may need to be removed at the next FFMPEG sync or when Apple deprecates the flag.
Fixes [Issue 808](https://github.com/MythTV/mythtv/issues/808)
> OSX: Fix FFMPEG Xcode15 linker issue

- mythplugins/mythmusic/mythmusic/musiccommon.cpp
- mythplugins/mythmusic/mythmusic/visualize.cpp
Continuing #801,
* 2 key now toggles text frequency overlay in Spectrogram
* 2 key also toggles text overlay in Spectrum and WaveForm, along with SELECT
* DELETE key clears WaveForm, in case you want to see it drawn again
* fixed bug that starting a stopped radio stream from full screen visual started music instead
I'll add this and more details to the manual soon.
> MythMusic: DELETE key clears WaveForm, 2 key toggles text on Spectrogram

- .github/workflows/buildmaster.yml
- mythtv/configure
- mythtv/programs/scripts/hardwareprofile/MultipartPostHandler.py
- mythtv/programs/scripts/hardwareprofile/distros/mythtv_data/request.py
- mythtv/programs/scripts/hardwareprofile/distros/mythtv_data/uuiddb.py
- mythtv/programs/scripts/hardwareprofile/hwdata.py
- mythtv/programs/scripts/hardwareprofile/os_detect.py
- mythtv/programs/scripts/hardwareprofile/request.py
- mythtv/programs/scripts/hardwareprofile/scan.py
- mythtv/programs/scripts/hardwareprofile/smolt.py
- mythtv/programs/scripts/hardwareprofile/uuiddb.py
Two commits:
- hardwareprofile: remove external dependency on simplejson
This uses the requests module and converts requests responses to json using requests' own `.json()` method on responses. For incomprehensible reasons, requests has spent about a decade using either simplejson or the standard library's json module more or less at will, and returning either one or the other exception types. They don't know why they use simplejson, we don't know why they use simplejson. In requests 3 (which will be released in the Year Of The Linux Desktop or when pigs fly, whichever one comes later) simplejson is dropped entirely.
There are innumerable issues discussing the problem on the requests bugtracker, with the general consensus being that it's better to randomly return either one of two …
> hardwareprofile: drop ancient python2 compatibility libraries: "future" and "simplejson"

- mythtv/programs/scripts/metadata/Music/lyrics/genius.py
- mythtv/programs/scripts/metadata/Music/lyrics/lyricswiki.py
The simplejson module was added to the python standard library in 2.6; here, it is inconsistently imported for python 2.6 (where it already exists) and lower (where it does not) instead of using `json`.
But, mythtv only supports python 3.8 for a while now. So this conditional is merely dead code. The import name is still aliased using `as simplejson`, though, which is bad for visibility and analysis.
Part of #824
> metadata/Music: remove unused external dependency on simplejson

- .github/workflows/buildmaster.yml
Python 3.12 removes the imp module but python-future v0.18.3 uses it,
see PythonCharmers/python-future#625
Since 4b5eac8, python-future is not needed anymore.
> Github workflow: Remove external dependency on python-future

- mythtv/libs/libmythbase/dbutil.cpp
- mythtv/libs/libmythbase/dbutil.h
- mythtv/libs/libmythtv/dbcheck.cpp
Take two on this.  I added a method to DBUtil to check for a column's presence.
.25 databases would migrate to .33 without aborting during the process. However, there were a number SQL errors that still appeared during migration. The major thing I noticed is that the "Default" recording template was not getting created. That insert fails due to missing columns and columns that do not allow null values.
The code to add these missing columns and modify nullable attributes is already present, but it is executed after the changes are actually required. Presumably, some later code changes broke some of the earlier migrations.
This time I removed none of the existing SQL changes. I only copied various SQL structure changes/data updates to earlier db version updates.  I then modified the later …
> Tweak structure changes to allow older MythTV databases to migrate cleanly.

- mythtv/i18n/mythfrontend_de.ts
This string was added recently, and needed translation
> Translate new string

- mythtv/libs/libmythbase/programinfo.cpp
- mythtv/libs/libmythtv/tv_play.cpp
- mythtv/programs/mythfrontend/globalsettings.cpp
- mythtv/programs/mythfrontend/mythfrontend.cpp
- mythtv/programs/mythfrontend/mythfrontend.pro
- mythtv/programs/mythfrontend/playbackbox.cpp
- mythtv/programs/mythfrontend/playbackbox.h
- mythtv/programs/mythfrontend/playbackstate.cpp
- mythtv/programs/mythfrontend/playbackstate.h
- mythtv/programs/mythfrontend/videodlg.cpp
- mythtv/programs/mythfrontend/videodlg.h
This adds support of displaying the bookmark state and the watched progress
within the video manager.
I have added preliminary support to display bookmark state and watched progress to the Monochrome theme
as seen in the image below:
> Support displaying bookmark state and watched progress in video manager

- mythplugins/mythmusic/mythmusic/streamview.cpp
- mythplugins/mythmusic/mythmusic/visualize.cpp
A track length of zero milliseconds is most likely wrong but can accidentally happen.  Rather than crash on divide by zero
later, let's pretend it is 1 minute long.  If the file plays successfully, then it should record the correct track length
and be more correct next time.
Also push fullscreen vis to the top of the stream menu since it is used more than add/edit/remove
> MythMusic: WaveForm: Fix divide by zero crash on zero track length

- .github/workflows/buildmaster.yml
Updates include:
- Updates for macos-14 runer which is arm64, but allows compilation on x86_64 via Rosetta 2
- The addition of a manual workflow trigger (allows a developer to run the CI on a branch other than master)
- lint clean up based on yamllint
> Github Workflow - Add macos-14 for both arm64 and x86_64

- mythtv/contrib/maintenance/mythtv-balance-expire
For distributing auto-expire recordings over multiple local disks across all recorded time.  This ensures all disks are expiring only the oldest files.
For details on why I like this, see the README at https://github.com/twitham1/mythtv-balance-expire which is also built into the program as `--help` and `--man`.  You can simply run this to try it out as it does nothing but report by default.  I have been running it monthly by cron for over 5 years.
> Add contrib/maintenance/mythtv-balance-expire

- mythtv/configure
Detection of libglslang by the configure script fails on Fedora 39 for MythTV version 34. Detection in master works good, so this is the backport of that code into the configure of MythTV version 34.
> Fix detection of libglslang in configure

- cmake/externallibs/FindOrBuildExiv2.cmake
- mythtv/cmake/MythFindPackages.cmake
- mythtv/configure
- mythtv/external/external.pro
- mythtv/libs/libmythmetadata/test/test_lyrics/test_lyrics.pro
- mythtv/libs/libmythmetadata/test/test_metadatagrabber/test_metadatagrabber.pro
- mythtv/libs/libmythmetadata/test/test_musicmetadata/test_musicmetadata.pro
- mythtv/libs/libmythmetadata/test/test_musicutils/test_musicutils.pro
- mythtv/libs/libmythmetadata/test/test_videometadata/test_videometadata.pro
- mythtv/programs/mythbackend/test/test_recordingextender/test_recordingextender.pro
- mythtv/programs/mythfrontend/test/test_videolist/test_videolist.pro
---
While initially C++17 support was not expected to be available until version 1.0, for various organizational reasons 0.28 includes the needed support.
There are currently few distros with 0.28.
NOTE: Compile tested only
> Support system distro version of exiv2 0.28 with includes C++17 support

- mythtv/libs/libmythtv/recorders/hdhrstreamhandler.cpp
The first step is to improve the error messages. In two
places the "UpdateFilters called in wrong tune mode"
message has been updated to specify the value of the
wrong tune mode.
After these updates, an example of the error message is:
_mythbackend: mythbackend[779282]: E HDHRStreamHandler
hdhrstreamhandler.cpp:242 (UpdateFilters) HDHRSH\[4\]
(13249773): UpdateFilters called in wrong tune mode, 4_
The tune mode was **hdhrTuneModeVChannel** (= 4), and
we know that **UpdateFilters** was called, but in
hdhrstreamhandler.cpp, the only call to it is avoided for
Vchan tuning.
```
108 void HDHRStreamHandler::run(void)
...
140             UpdateFiltersFromStreamData();
141             if (m_tuneMode != hdhrTuneModeVChannel)
142                 UpdateFilters();
```
Code examination reveals that …
> Avoid removing PID filters when using virtual channel tuning

- mythtv/docs/CMakeLists.txt
- mythtv/docs/Makefile
- mythtv/docs/doxygen-architecture-document.cpp
- mythtv/docs/doxygen-create-developer-docs.cfg
- mythtv/docs/doxygen-paths.cfg.inc.in
This should help to make the docs more useful.  
@linuxdude42 I'm not sure how to test the cmake changes, but I followed what you did.
> Update Doxygen doxyfile

- mythtv/external/FFmpeg/libavformat/mpegts-mythtv.c
- mythtv/external/FFmpeg/libavformat/mpegts-mythtv.h
- mythtv/external/FFmpeg/libavformat/mpegts.c
- mythtv/external/FFmpeg/libavformat/mpegts.h
- mythtv/external/FFmpeg/libavformat/rtpdec_mpegts.c
- mythtv/external/FFmpeg/libavformat/rtsp.c
- mythtv/external/FFmpeg/libavformat/wtvdec.c
- mythtv/programs/mythbackend/CMakeLists.txt
The GitHub Actions Fedora CMake builder is now building libavdevice/iec61883.c which includes and uses FFmpeg’s mpegts.h, causing it to not compile.
> GitHub Actions: fix Fedora CMake build

- mythtv/libs/libmythtv/osd.h
Compiling tv_play.cpp gives a few compiler warnings like this: tv_play.cpp: In member function ‘void TV::ShowOSDAskAllow()’: tv_play.cpp:1739:73: warning: missing initializer for member ‘MythOSDDialogData::m_buttons’ [-Wmissing-field-initializers]
1739 |         MythOSDDialogData dialog { OSD_DLG_ASKALLOW, message, timeuntil };
and
tv_play.cpp: In member function ‘void TV::StartChannelEditMode()’:
tv_play.cpp:7857:29: warning: missing initializer for member ‘MythOSDDialogData::m_message’ [-Wmissing-field-initializers]
7857 |         emit ChangeOSDDialog({ OSD_DLG_EDITOR })
These warnings can be fixed by initializing m_buttons and m_message in osd.h.
> Fix GCC warnings about missing initializers

- mythtv/libs/libmythtv/bitreader.h
- mythtv/libs/libmythtv/bytereader.cpp
This is a change to make ByteReader not depend on FFmpeg and some minor tweaks to BitReader.  The only functional change is in the last commit in regards to how BitReader responds when the data it is reading has been modified since it was constructed (which should never happen).  See the individual commits for details.
> BitReader cleanup

- .github/workflows/build-mythtv.yml
The macOS 14 runner hardware is arm64 requiring the x86_64 build to
cross-compile via rosetta2.  Unfortunately, this cross-compile
mechanism has a tendency to stall out leading to false negatives in
the CI process.
> Github workflow: Remove macOS cross-compile for macOS14

- mythtv/bindings/python/tmdb3/tmdb3/lookup.py
tmdb3 lookup.py does not allow queries for tv-season number 0
as raised by @davidjo in #902.
Provided patch in #902 works for me, tested with:
```
tmdb3tv.py -l en -a GB -D 62974 0 5
tmdb3tv.py -l de -a AT -D 53193 0 3
```
otherwise, one gets:
```
~/MythTV/issue_902$ ./share/mythtv/metadata/Television/tmdb3tv.py -l en -a GB -D 62974 0 5
Traceback (most recent call last):
File "~/MythTV/issue_902/./share/mythtv/metadata/Television/tmdb3tv.py", line 159, in <module>
sys.exit(main("television",'tmdb3tv.py'))
File "~/MythTV/issue_902/./share/mythtv/metadata/Television/tmdb3tv.py", line 136, in main
xml = buildEpisode(args[0:3], opts)
File "~/MythTV/issue_902/MythTV/tmdb3/lookup.py", line 397, in buildEpisode
if season.poster:
UnboundLocalError: local variable 'season' referenced before …
```
> Python tmdb3tv: Allow specials with season number 0

- mythplugins/mythbrowser/mythbrowser/libmythbrowser.cpp
- mythplugins/mythgame/mythgame/mythgame.cpp
- mythplugins/mythmusic/mythmusic/mythmusic.cpp
- mythplugins/mythnews/mythnews/libmythnews.cpp
- mythplugins/mythweather/mythweather/mythweather.cpp
- mythtv/keybindings.txt
- mythtv/libs/libmythtv/tv_play.cpp
- mythtv/libs/libmythui/mythmainwindow.cpp
- mythtv/programs/mythfrontend/mythfrontend.cpp
Appears that USB HID standardized common media control keys some years after MythTV was invented.  These have Keysyms in X11 and then Qt for several years now but it wasn't until 2019 and later that web browsers finally started supporting these keys.
So rather than all users manually mapping these, seems MythTV should support them out of the box.  Home Page makes a great Info button on the MX3 but might be in an odd place on other remotes.  But if this key is anywhere and makes it to MythTV it might as well do something useful, right?  All others are hopefully self explanatory.
While here, also map emacs-like Ctrl+B and Ctrl+F for rewind and fast foward as on older MCE remotes like ARC-1100.  This required moving "jump to start" from Ctrl+B to Ctrl+A.  Menu, Info and Delete are also …
> Support USB HID media control keys now common on remotes and keyboards.

- platform/win32/w64-mingw32/Installer/1 Install Mythtv.cmd
* Curl now uses the parameter "-k"
* Bump xampp version to 8.0.25. 
* Remove parameter -r from rmdir
* For aesthetics, add verbose "-v" parameter to tar
* To mysql command add the parameter "--skip-password"
* For aethetics very the by querying and viewing the new user "mythtv" in the mysql database
```
C:\INSTALL>curl -L "https://sourceforge.net/projects/xampp/files/XAMPP%%20Windows/8.0.9/xampp-portable-windows-x64-8.0.9-0-VS16.zip/download" > xampp-portable-windows.zip)
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was …
```
> fixes to 1 Install Mythtv.cmd

- mythtv/libs/libmythtv/libmythtv.pro
- mythtv/libs/libmythtv/mpeg/H2645Parser.h
- mythtv/libs/libmythtv/recorders/dtvrecorder.h
- mythtv/libs/libmythtv/recorders/recorderbase.h
- mythtv/libs/libmythtv/scantype.h
This is intended to reduce unnecessary transitive includes in the H.264 and H.265 parsers, particularly "libavcodec/avcodec.h".
This was separated out from an upcoming change to create a MythAVRational wrapper class.
> SCAN_t: move to its own header

- mythplugins/mythmusic/mythmusic/musicdbcheck.cpp
- mythtv/libs/libmythtv/dbcheck.cpp
> eliminate 'goto's in dbcheck.cpp and musicdbcheck.cpp

- .github/workflows/build-mythtv.yml
Per https://github.com/actions/runner-images/issues/10721
macOS 12 will be removed from github action runners on
12/03/24.
Remove the CI build from the workflow
> Remove macOS 12 CI build job from the actions workflow

- mythtv/programs/mythbackend/scheduler.cpp
The comparing message has been updated to specify
both programs, and to show the channels for those
programs.
The "groupmplexid's" message has been updated to
separate the words which have been smashed
together.
Resolves: #967
> Improved scheduler log messages

- mythtv/libs/libmythtv/channelscan/iptvchannelfetcher.cpp
Add a simple EXTINF format in the IPTV channel fetcher that can parse the format "EXTINF:0,Channel_Title".
Refs #936
> Add EXTINF format

- mythtv/programs/mythbackend/backendhousekeeper.cpp
Delete all IPTV channel data extensions records from the database when the channel it refers to does not exist anymore.
As part of the periodic housekeeping tasks all channels that have been marked for deletion and for which there are no more recordings preseent are removed from the database. For IPTV channels the IPTV URL is stored in table iptv_channel. This table can be seen as an extension of table channel and it is usually accessed with the chanid from the channel table. This means that when a channel is really deleted (removed from the database) also the corresponding record in iptv_channel has to be deleted.
Refs #936
> Delete IPTV channel data when the channel is removed

- mythtv/libs/libmythtv/cardutil.cpp
The CardUtil function DeleteAllInputs does delete the content of all four tables related to inputs but it does also delete the content of table iptv_channel.
This is not correct; table iptv_channel contains the URLs of the channels that are IPTV channels.
This bug has been introduced as part of commit d4c0f13. The entries in table iptv_channel can only be removed when the corresponding channel has been deleted.
This is done as part of a periodic housekeeping task.
Refs #936
> DeleteAllInputs must not delete iptv_channel

- mythtv/libs/libmythtv/tvbrowsehelper.cpp
- mythtv/libs/libmythtv/tvbrowsehelper.h
When starting TV playback, either from a recording or live, a list of all channels is created that can be used to select another channel with the up/down keys while watching.
This channel list is created twice; as the name implies one for all channels and one for all visible channels. However, both lists are identical and contain all channels. The check on visible or not was already been done somewhere else in the code.
Therefore only one list with all channels is needed. Note that the time to create this list can be significant when there are a large number of channels. With satellites and especially with IPTV the number of channels can easily become very large, as in several thousands.
> Remove duplicate browse channel list

- mythtv/libs/libmythtv/channelutil.cpp
The function DeleteChannel does not really delete a channel but marks it for deletion when it is no longer referenced. This is introduced in commit 2e26f7f12fce13c155e43ff536b1e09a342e1722. Because the channel is not really deleted, as in removed from the database, the associated record in table iptv_channel should also not be deleted here.
The channel is removed from the database in a periodic housekeeping task when there are no more recordings referencing that channel and when at least one day has passed since the channel was marked for deletion.
When the channel is finally deleted then also the corresponding entry in iptv_channel, when it exists, should be deleted.
> Do not delete IPTV channel in DeleteChannel

- mythtv/libs/libmythtv/captions/subtitlereader.cpp
Some types of subtitle, rather than being tagged with a duration, rely on the next in sequence to clear them, specifically with an empty subtitle at the end of the sequence. AddAVSubtitle has to handle forced subtitles, causing them to be displayed even when subtitles are off. It was detecting a subtitle being forced by looking for a "forced" flag amongst the subtitle's rectangles. That failed to detect the case of an empty subtitle. Hence the last non-empty forced subtitle was not being cleared by the subsequent empty one. This commit changes the detection condition, using instead a flag that denotes whether the subtitle is from the currently selected forced track.
This fixes Issue #978
> Fix failure to clear last forced subtitle in a sequence

- mythtv/libs/libmythtv/eitfixup.cpp
- mythtv/libs/libmythtv/eithelper.cpp
- mythtv/libs/libmythtv/test/test_eitfixups/test_eitfixups.cpp
* Update EIT fixes for ProSiebenSat.1 (Europe): EIT of ProSiebenSat.1 has changed years ago, old fixes do not work any more. ProSiebenSat.1 still dumps all kind of metadata into the subtitle field from where it can be retrieved.
* Remove most fixes for Kabel Deutschland: EPG of Vodafone's (formerly Kabel Deutschland) DVB-C is much better today, most fixes are superflous now. Due to frequency/channel changes, the old fixes did not work any more anyway. Only use updated fixes for ProSiebenSat.1
* Remove fixups for German DVB-T: Service got disabled in 2019.
> Clean up EIT fixes for ProSiebenSat.1 and Vodafone Germany

- mythtv/libs/libmythtv/channelutil.cpp
Use isEmpty instead of isNull in ChannelUtil::UpdateChannel to handle both an empty string and no string in the same way. With an IPTV channel rescan the existing values of xmltvid and icon are now preserved when there are no new values found in the scan.
Refs #973
> Use isEmpty instead of isNull in UpdateChannel

- mythtv/libs/libmyth/test/test_audioutils/test_audioutils.h
Use `memset()` instead of type punning for memory poison.
> test_audioutils: silence -Wstrict-aliasing

- mythtv/libs/libmythtv/HLS/m3u.cpp
- mythtv/libs/libmythtv/recorders/httptsstreamhandler.cpp
Set download status to not OK when a network error is reported for the download. This fixes an endless loop / log pollution when server access is not allowed, reported as  error 201 (HTTP error 403).
> IPTV Download not OK with network error

- mythtv/libs/libmythtv/recordinginfo.cpp
No functional change.
bindValueNoNull was introduced in 19a51cb405 and some codes previously migrated.  Take another step in the migration for recordinginfo.cpp (similar fixes were introduced in 334c4cf242, 28e98a80ed (and probably others)).
----
If accepted (and PR #963 merged) I'll also look at migrating programdata.cpp to bindValueNoNull
> Migrate from bindValue(..., null_to_empty(x)) to bindValueNoNull(..., x)

- mythtv/programs/scripts/database/mythconverg_backup.pl
- mythtv/programs/scripts/database/mythconverg_restore.pl
While trying to move my mythbackend sql database to my syndology nas (which uses port 3307 for its mariadb server) I discovered that mythconverg_restore.pl and mythconverg_backup.pl don't honour the port setting in config.xml when trying to login to the mysql server.
Confirmed working using mythtv/31 on my pi4 gentoo based mythtv installation
> honour port setting in mythconverg backup/restore perl scripts

- mythtv/external/libmythdvdnav/CMakeLists.txt
The commit fixes the following error, trying to link libmythdvdnav
/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_open'
/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_close'
/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_open_stream'
/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_read'
/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_seek'
collect2: error: ld returned 1 exit status
> Fix cmake compilation with dvdcss

- mythtv/libs/libmythtv/decoders/mythv4l2m2mcontext.cpp
- mythtv/libs/libmythtv/decoders/mythv4l2m2mcontext.h
These are some changes that should help prepare for planned V4L2 Request API hwaccel changes.
Please note that I have not compile or runtime testes these changes, @warpme please help test these changes.
> MythV4L2M2MContext: Prepare for planned V4L2 Request API hwaccel changes

- mythtv/libs/libmythtv/CMakeLists.txt
- mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
- mythtv/libs/libmythtv/decoders/decoderbase.cpp
- mythtv/libs/libmythtv/decoders/decoderbase.h
- mythtv/libs/libmythtv/libmythtv.pro
- mythtv/libs/libmythtv/mpeg/AVCParser.cpp
- mythtv/libs/libmythtv/mpeg/AVCParser.h
- mythtv/libs/libmythtv/mpeg/H2645Parser.cpp
- mythtv/libs/libmythtv/mpeg/H2645Parser.h
- mythtv/libs/libmythtv/mpeg/HEVCParser.cpp
- mythtv/libs/libmythtv/mpeg/HEVCParser.h
- mythtv/libs/libmythtv/mythavrational.h
- mythtv/libs/libmythtv/recorders/NuppelVideoRecorder.cpp
- mythtv/libs/libmythtv/recorders/dtvrecorder.cpp
- mythtv/libs/libmythtv/recorders/dtvrecorder.h
- mythtv/libs/libmythtv/recorders/recorderbase.cpp
- mythtv/libs/libmythtv/recorders/recorderbase.h
This was mostly to replace the partial wrapper FrameRate with a more complete one.  I also made some further conversions to MythAVRational, but there is much more that could be converted.
> Create MythAVRational to wrap AVRational

- mythtv/bindings/python/tmdb3/tmdb3/lookup.py
- mythtv/libs/libmythmetadata/metadatadownload.cpp
- mythtv/libs/libmythmetadata/test/test_videometadata/test_videometadata.h
- mythtv/libs/libmythmetadata/videometadata.cpp
MythTV parses filenames of movies and series according
the scheme defined in
https://www.mythtv.org/wiki/MythVideo_File_Parsing
For tv-series, it is allowed to add the year in the title,
like `The Forsyte Saga (1967)` or `The Forsyte Saga (2002)`,
e.g.: `The Forsyte Saga (1967) 1x01 A Family Festival.mkv`
is correctly parsed.
This may help the television grabber of MythTV to find the
correct entry.
In contrast, all kind of braces are removed from the filename
when parsing video titles:
`Ocean's Eleven (2001).mp4` becomes `Ocean's Eleven 2001`
according the filename convention on the wiki.
This confuses the movie grabber of MythTV because it
cannot be distinguished whether the year is part of the
title or it is the year of the release. For exact this reason,
grabbing for titles ending with …
> Harmonize Title-Parsing of Movies and TV-Series

- mythtv/bindings/python/MythTV/utility/dt.py
- mythtv/bindings/python/tmdb3/tmdb3/locales.py
- mythtv/bindings/python/tmdb3/tmdb3/lookup.py
Python 3.11 deprecates the API locale.getdefaultlocale() with a pending removal in Python 3.13 (I).
Python 3.12 moves this pending removal to Python 3.15 (II). 
Deprecation warnings in Python 3.12:
datetime: datetime.datetime’s utcnow() and utcfromtimestamp() are deprecated and will be removed in a future version. Instead, use timezone-aware objects to represent datetimes in UTC: respectively, call now() and fromtimestamp() with the tz parameter set to datetime.UTC. (Contributed by Paul Ganssle in gh-103857.) See (II).
References:
(I)  https://docs.python.org/3/whatsnew/3.11.html#deprecated
(II) https://docs.python.org/3/whatsnew/3.12.html#deprecated
Fixes #819
> Python: Fix deprecation warnings in 3.11+

- cmake/platform/DarwinCustomization.cmake
FFMPEG 7.1 introduces a new issue where "Host C11" testing fails due
due to configure not being able to find system support libraries.
A similar/related issue was fixed previously where --extra-cflags
and --extra-ldflags needed to be set to point configure to the
system includes and libraries.
To resolve this, the host-cflags and host-ldflags options must be
set to the same values as --extra-cflags and --extra-ldflags. The
--host-cppflags and --extra-cxxflags were added for completeness.
An additional update included searching the compiler for either
Xcode or CommandLineTools as the user may have selected one or
the other with xcode-select -s. In either case, the correct path
to the respective SDK's is stored in OSX_SDK_ROOT, so use that path
vs. the previous hard code.
Thank you for …
> macOS: fix FFMPEG 7.1 host compiler lacks C11 support issue on macOS

- mythplugins/mythmusic/mythmusic/musiccommon.cpp
MythMusic: Promote Fullscreen Vis to first menu item
to match stream view and because list edits are done less frequently.
Also drop non-working menu entries from full screen visualizer.
> MythMusic: Promote Fullscreen Vis to first menu item

- .github/workflows/build-mythtv.yml
Migrate to a homebrew based workflow now that the qt-mariadb/qt-mysql formula is available.
> github actions: Update github workflow to use homebrew, add macOS 15 runner

- .github/workflows/build-mythtv.yml
- cmake/SourceVersion.cmake
This PR attempts to fix a cmake issue where branches / forks may not have any describe data.  It additionally adds missing tests to the linux cmake test builds and migrates the macOS workflow to cmake/qt6.
> github: Add missing cmake test and migrate macOS to cmake/qt6 based builds

- platform/darwin/notarizeFiles.zsh
> cmake: fix macOS notarization typo

- mythplugins/mythmusic/mythmusic/mythmusic.cpp
- mythtv/libs/libmythui/mediamonitor.cpp
- mythtv/libs/libmythui/mediamonitor.h
- mythtv/programs/mythfrontend/mythfrontend.cpp
Add support to play an audio CD from the 'Play Optical Disc' menu. The media monitor callback function was extended by a 'forcePlayback' parameter which will override the auto play option for some of the media handlers when started explicitly by the user via the menu.
> Support playing Audio CD from optical disc menu

- mythtv/libs/libmythtv/Bluray/mythbddecoder.cpp
- mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
- mythtv/libs/libmythtv/decoders/avformatdecoder.h
call avformat_find_stream_info() only once
It frees FFStream::info, which will cause a segmentation fault on a second call
since info will be NULL.
silence_ffmpeg_logging is never set and -1 is not an AVERROR code (depends on
the values used by errno.h), so those can be removed.
Closes https://github.com/MythTV/mythtv/issues/1035.
> Fix Blu-ray crashes

- .github/workflows/build-mythtv.yml
Github and homebrew occasionally get out of sync with the python
package.  Fix this by brute force uninstalling python and its
dependents, updating homebrew, then reinstalling python.  Necessary
dependents should get reinstalled by ansible.
> Github: fix broken macOS 13 python

- mythtv/libs/libmythbase/mythcommandlineparser.cpp
- mythtv/programs/mythbackend/mythbackend_main_helpers.cpp
- mythtv/programs/mythjobqueue/mythjobqueue.cpp
- mythtv/programs/mythmediaserver/mythmediaserver.cpp
- mythtv/programs/mythtv-setup/mythtv-setup.cpp
Also improve code creating and deleting the pidfile for mythbackend.
Expanded version of a commit from https://github.com/MythTV/mythtv/pull/671.
> remove unused pidfile and logfile global variables

- mythplugins/mytharchive/mytharchive/videoselector.cpp
- mythplugins/mythnetvision/mythnetvision/netbase.cpp
- mythtv/libs/libmythbase/storagegroup.cpp
- mythtv/libs/libmythbase/storagegroup.h
- mythtv/libs/libmythmetadata/metadatafactory.cpp
- mythtv/libs/libmythmetadata/videometadata.cpp
- mythtv/libs/libmythmetadata/videoscan.cpp
- mythtv/libs/libmythmetadata/videoutils.h
- mythtv/libs/libmythtv/metadataimagehelper.cpp
- mythtv/libs/libmythtv/videodbcheck.cpp
- mythtv/programs/mythfrontend/editvideometadata.cpp
- mythtv/programs/mythfrontend/scheduleeditor.cpp
- mythtv/programs/mythfrontend/services/frontend.cpp
- mythtv/programs/mythfrontend/services/mythfrontendservice.cpp
- mythtv/programs/mythfrontend/setupwizard_video.cpp
- mythtv/programs/mythfrontend/videodlg.cpp
- mythtv/programs/mythfrontend/videoplayercommand.cpp
This breaks the dependency of libmythtv on libmythmetadata.
This was originally part of https://github.com/MythTV/mythtv/pull/671
> move generate_file_url() from libmythmetadata to libmythbase

- mythtv/libs/libmythmetadata/imagemetadata.cpp
- mythtv/libs/libmythmetadata/imagemetadata.h
- mythtv/libs/libmythmetadata/imagescanner.cpp
- mythtv/libs/libmythmetadata/imagethumbs.cpp
- mythtv/programs/mythfrontend/galleryslide.cpp
The current QT5_MIN_VERSION_STR is 5.15.2.
This was originally part of https://github.com/MythTV/mythtv/pull/671.
> libmythmetadata/imagemetadata: remove Qt 5.4.1 specific code

- .github/workflows/build-mythtv.yml
On macOS Ventura, the azure-cli homebrew formula has not correctly
been updated to use python3.13 causing a brew link error when
updating the underlying homebrew formula.  Since its not needed
remove the azure-cli package.
> GitHub: macOS Fix broken azure-cli python3.12 link

- mythtv/libs/libmyth/libmyth.pro
- mythtv/libs/libmythupnp/httpserver.cpp
- mythtv/libs/libmythupnp/httpserver.h
- mythtv/programs/mythbackend/mediaserver.cpp
- mythtv/programs/mythexternrecorder/CMakeLists.txt
- mythtv/programs/mythexternrecorder/mythexternrecorder.pro
- mythtv/programs/mythfilerecorder/CMakeLists.txt
- mythtv/programs/mythfilerecorder/mythfilerecorder.pro
mythbackend.pro still needs using_qtscript: QT += script due to transitive includes from libmythupnp/htmlserver.h
> remove unnecessary references to QtScript

- platform/darwin/CMakeLists.txt
Please apply to both master and fixes/35
A regression in qt 6.9.0 introduces a bug where macdeployqt
cannot locate certain QT libraries referenced via rpath where those
libraries do not have an id field with rpath in the id.  Creating
a symlink to the package manger directory in the directory
where macdeployqt will be called is a documented work around.
https://github.com/orgs/Homebrew/discussions/2823#discussioncomment-8735051
> cmake: Fix macdeployqt 6.9.0 rpath issue

- mythtv/bindings/python/MythTV/utility/dt.py
Python3.13 takes the `fold` attribute into account when crating various `MythTV.datetime` objects. This attribute is used to disambiguate `datetime` objects during transition from daylight saving time to standard time, where the local time stamp occurs twice.
Found in the changelog of python 3.13:
gh-89039: When replace() method is called on a subclass of datetime, date or time, properly call derived constructor. Previously, only the base class’s constructor was called.
Also, make sure to pass non-zero fold values when creating subclasses in various methods. Previously, fold was silently ignored.
Refs: MythTV.#1083
> Python: Respect `fold` attribute provided by `datetime.tzinfo`

- mythtv/libs/libmythui/platforms/mythscreensaverdbus.cpp
Always return false for the Asleep function of the DBus screensaver.
Remove the inhibite state bookkeeping because that is not used anymore.
The Asleep function is only relevant for the X11 screensaver.
The value of this function is used in mythinputdevicehandler.cpp to discard input events when the screen is powered off. This is only useful with the X11 screensaver; the DBus screensaver has the state "inhibited" and "not inhibited" but it does not say anything about the screen actually being saved or not.
Fixes #1064
> DBus screensaver always report being awake

- mythtv/libs/libmyth/audio/audiooutputpulse.cpp
On a system using PulseAudio, when you Play a recording and then  Stop that play session, four files get left open. This resource leak keeps adding up until the Soft Limit for file descriptors gets exceeded. The next attempt to Play will cause the **mythfrontend** to crash. On Linux the default Soft Limit is 1024, but the application consumes 471 files before the first time you Play. Every time you Play a recording, or start and stop watching Live TV, these file resources leak.
According to the PulseAudio Destruction documentation :
"When the PulseAudio connection has been terminated, the thread must be stopped and the resources freed. Stopping the thread is done using **pa_threaded_mainloop_stop()**, which must be called without the lock (see below) held. When that function returns, the …
> Close file leak in PulseAudio output handler

- mythtv/libs/libmythui/platforms/mythnvcontrol.cpp
According to the Nvidia header file, when invoking XNVCTRLQueryTargetBinaryData(), it is the caller's responsibility to free the data when done.
This modification adds the step of freeing the
memory allocated for 'data'.
Resolves: #1102
> Close memory leak in GetDisplayID

- mythtv/CMakeLists.txt
- mythtv/libs/libmythtv/test/test_copyframes/test_copyframes.cpp
- mythtv/libs/libmythtv/test/test_copyframes/test_copyframes.h
This should show exactly what failed in the GitHub Actions for builds using CMake.
> have CTest print test output on failure

- mythtv/libs/libmythbase/mythsorthelper.cpp
The usage of **std::make_shared<>** was improper. The whole point of this template is to automatically allocate memory and invoke the constructor. By eliminating an unnecessary 'new' call in this code, we remove the memory leak. In addition, we simplify the invocation by removing the unnecessary constructor call. **std::make_shared<>** only requires the constructor arguments. Proper template usage makes it safer, faster, and less leaky.
Resolves #1106
> Close memory leak in getMythSortHelper

- mythtv/libs/libmythbase/logging.cpp
The verboseMap and loglevelMap entities are of type QMap. When the values inserted into a QMap are from allocated memory, the recommended way to clean up, is to invoke
```
qDeleteAll( map ); // delete all values in map
map.clear(); // remove map references to values
```
In verboseAdd(), new VerboseDef is invoked.
In loglevelAdd(), new LoglevelDef is invoked.
To properly clean up without a memory leak, in logStop() and verboseInit() we need to call qDeleteAll() and clear().
Resolves #1104
> Close memory leak in loglevelAdd()

- mythtv/libs/libmythui/platforms/mythdisplayx11.cpp
A call to XRRGetOutputProperty() allocates memory and assigns it to the 'prop' argument. In mythdisplayx11.cpp, the 'data' variable is
passed in as the 'prop' argument, so we need to free the memory which gets assigned to 'data'.
Resolves #1105
> Close memory leak in MythDisplayX11::GetEDID

- mythtv/libs/libmythui/opengl/mythrenderopengl.h
At the allocation point a **MythVideoTextureOpenGL** class was created. At the deletion point, a **MythGLTexture** was released. MythGLTexture is a base class for **MythVideoTextureOpenGL**.
If you intend to delete a derived class object through a base class pointer, the base class must have a virtual destructor. This ensures that the correct destructor for the derived class is called when the object is deleted.
This modification stipulates the destructor for **MythGLTexture** to be virtual. This ensures that the type upon deletion matches the type upon creation.
Resolves #1121
> Fix New, Delete type mismatch

- mythtv/libs/libmyth/audio/audiooutputpulse.cpp
- mythtv/libs/libmyth/audio/audiooutputpulse.h
The original code allocated memory with calls to **pa_proplist_new()**, and stored those addresses in a local variable, _proplist_. The corresponding memory was never released. The same local variable was used in two different methods, **ContextConnect()** and **ConnectPlaybackStream()**.
We need to keep track of these memory pointers separately, so 2 new members have been added to the AudioOutputPulseAudio class:
```
pa_proplist *m_ctproplist
pa_proplist *m_stproplist
```
When memory is allocated for Context or Stream, the updated code stores the _pa_proplist *_ value in _m_ctproplist_ or _m_stproplist_. Later on, when it's time to release memory, these class members are used in calls to **pa_proplist_free()**.
A separate memory leak was identified in the call to **pa_context_drain()**. …
> Close memory leaks in PulseAudio output handler

- mythtv/libs/libmythbase/signalhandling.cpp
This modification of the **SignalHandler** destructor adds the missing delete of memory allocated for the **m_sigStack** array.
Resolves #1112
> Close memory leak in SignalHandler

- mythtv/libs/libmythtv/captions/cc708decoder.cpp
- mythtv/libs/libmythtv/captions/cc708decoder.h
- mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
ANSI/CTA-708-E S-2023 page 14 footnote 4:
"The presence of padding should not be interpreted as terminating the CCP." The fix from f8312c35f01980be8d10a048cc23220f11864211 is incorrect.
Instead, check if the CCP is full after adding data and parse immediately.
caption_channel_packet::packet_data_size is 127 for packet_size_code = 0, which parse_cc_packet() will still incorrectly skip.
The addition of m_partialPacket.size > 0 prevents data from being added to a packet before a header has been added.  size will remain 0 until a header is added and total_packet_size is never 0, so parse_cc_packet() will not be called until a header has been added.
Fixes https://github.com/MythTV/mythtv/issues/1117
> fix ANSI/CTA-708 DTV Closed Captions decoding

- mythtv/libs/libmythmetadata/metaioflacvorbis.cpp
- mythtv/libs/libmythmetadata/metaioflacvorbis.h
- mythtv/libs/libmythmetadata/metaioid3.cpp
- mythtv/libs/libmythmetadata/metaioid3.h
- mythtv/libs/libmythmetadata/metaiooggvorbis.h
- mythtv/libs/libmythmetadata/metaiotaglib.cpp
- mythtv/libs/libmythmetadata/metaiotaglib.h
- mythtv/libs/libmythmetadata/metaiowavpack.cpp
- mythtv/libs/libmythmetadata/metaiowavpack.h
This silences a warning from gcc about /usr/include/taglib/id3v2frame.h
> include TagLib headers using the taglib directory

- mythtv/libs/libmythtv/test/test_bitreader/CMakeLists.txt
@linuxdude42 You didn't adjust it when copying from a different test.
> fix CMake name for test_bitreader

- mythplugins/mythzoneminder/mythzmserver/zmserver.cpp
MSG_NOSIGNAL is defined in the GitHub Actions builders.
Make the condition agnostic to OS, which is how FFmpeg does it.
@linuxdude42 This should fix the GitHub Actions for macOS 13 and 14 since you re-enabled building zmserver https://github.com/MythTV/mythtv/commit/8f7766d62c6a3eb3630392b2ebf419d276d8fe40.
> fix compilation of zmserver.cpp on macOS

- mythtv/libs/libmythtv/channelsettings.cpp
- mythtv/libs/libmythtv/channelsettings.h
- mythtv/libs/libmythtv/playgroup.cpp
- mythtv/libs/libmythtv/profilegroup.h
- mythtv/libs/libmythtv/recordingprofile.h
- mythtv/libs/libmythtv/videosource.cpp
- mythtv/libs/libmythtv/videosource.h
- mythtv/libs/libmythui/standardsettings.cpp
- mythtv/libs/libmythui/standardsettings.h
- mythtv/libs/libmythui/storagegroupeditor.cpp
- mythtv/libs/libmythui/storagegroupeditor.h
All of the classes derived from **StandardSetting** which use 'new' to allocate their storage memory have been updated to add destructors which call "_**delete GetStorage()**_;" This frees up memory allocated from the heap when an instance of that class falls out of scope or is deleted. This closes the StandardSetting related memory leaks.
Resolves: MythTV#1120
> Close StandardSetting memory leaks using destructors

- mythtv/configure
* mythtv/external/libmythbluray/ won't be built
* java is required at runtime only
> configure: no ant & java required if use system libbluray

- platform/darwin/fixAppBundle.zsh
Add code to locate and correct missing Qt framworks "skipped" by
macdeployqt when bundling the mythfrontend app.  This issue only
occurs on homebrew based builds that use QtWebengine.
For some reason, QtQuickWidgets.framework does not get
copied into the app framework by macdeployqt. This update searches
for any missing Qt frameworks, copies the missing frameworks into the
app bundle, and corrects any libraries contained in the framework.
> macOS: fix missing qt framework issue during app packaging

- .github/workflows/build-mythtv.yml
This was causing TestCopyFrames to abort after
passing all of the tests on macOS 15.
> GitHub Actions: Disable LTO for macOS builds
