MythTV/mythtv

mythtv/libs/libmythbase/mythsingledownload.cpp
mythtv/libs/libmythbase/mythsingledownload.h
mythtv/libs/libmythtv/channelscan/iptvchannelfetcher.h
mythtv/libs/libmythtv/channelutil.cpp
mythtv/libs/libmythtv/channelutil.h
mythtv/libs/libmythtv/iptvtuningdata.h
mythtv/libs/libmythtv/libmythtv.pro
mythtv/libs/libmythtv/mythsystemevent.cpp
mythtv/libs/libmythtv/recorders/HLS/HLSReader.cpp
mythtv/libs/libmythtv/recorders/HLS/HLSReader.h
mythtv/libs/libmythtv/recorders/cetonstreamhandler.cpp
mythtv/libs/libmythtv/recorders/httptsstreamhandler.cpp
mythtv/libs/libmythtv/recorders/httptsstreamhandler.h
mythtv/libs/libmythtv/recorders/iptvchannel.cpp
mythtv/libs/libmythtv/recorders/iptvchannel.h
mythtv/libs/libmythtv/recorders/iptvstreamhandler.cpp
mythtv/libs/libmythtv/recorders/iptvstreamhandler.h
mythtv/libs/libmythtv/tv_rec.cpp
mythtv/libs/libmythtv/tv_rec.h

This pull request adds HTTP TS support into fixes/0.27.
It uses: 
* iptv_extension_01.patch from ticket #12168
* commit e740947 (rebased)

HTTPS TS support in fixes/0.27

---

mythplugins/mythmusic/i18n/mythmusic_en_gb.ts
mythtv/i18n/mythfrontend_en_gb.ts

Updated en_gb translations for the following MythTV components:
- MythFrontend
- MythMusic

Updated British English translations

---

mythtv/libs/libmythbase/mythmiscutil.cpp

The ping command on Linux based operating systems uses the -w
paremeter to specify the timeout in seconds.  The ping command on
FreeBSD based operating systems uses the -t parameter.  Use compile
time flags to generate the right ping command for the operating
system. 
Fixes https://code.mythtv.org/trac/ticket/12034.

Use correct ping timeout parameter for the operating system.

---

mythtv/bindings/python/MythTV/ttvdb/XSLT/tvdbVideo.xsl
mythtv/programs/scripts/metadata/Television/ttvdb.py

pull requests due to missing tickets.)
https://code.mythtv.org/trac/wiki/TicketHowTo
https://code.mythtv.org/trac/newticket

#13084 ttvdb fix runtime and genre

---

mythtv/libs/libmythtv/videodev2.h

Add __le32 and friends for FreeBSD.

FreeBSD does not have endian types

---

mythtv/libs/libmythtv/recorders/dvbchannel.cpp

m_is_open was being corrupted by multiple simultaneous modifications,
leading to it managing to create infinite loops within its underlying
data structure. This patch extends the locking of m_hw_lock to cover
all uses of m_is_open, preventing issues.

Prevent data corruption in dvbchannel.cpp causing hang

---

mythtv/version.sh

pull requests due to missing tickets.)
https://code.mythtv.org/trac/wiki/TicketHowTo
https://code.mythtv.org/trac/newticket

Fix typo in 0851b35e3ded43ea738473bc60b8e5d13595b922 comment

---

mythtv/libs/libmyth/mediamonitor-darwin.cpp

fix variable capitalization issues to allow successful compilation on macOS High SIerra

---

mythtv/libs/libmyth/audio/audioconvert.cpp
mythtv/libs/libmyth/audio/audiooutputca.cpp
mythtv/libs/libmyth/audio/audiooutpututil.cpp

Fix macOS 11 Big Sur audio issues by updating to audo code from master

---

mythtv/libs/libmyth/mediamonitor-darwin.cpp

Fix usleep call for older macOS versions (High Sierra)

---

mythtv/libs/libmythui/mythuibuttonlist.h

MythUIButtonListItem: Ensure all member vars are initialised

---

mythtv/configure

Fix linking with gold or lld by adding -lXext to linkage

---

mythtv/SRC_VERSION
mythtv/VERSION
mythtv/version.sh

Master: Rename VERSION file to SRC_VERSION to correct conflict with C++17 version header on case insensitive filesystems

---

mythplugins/mytharchive/mytharchivehelper/main.cpp
mythtv/libs/libmyth/programinfo.cpp

-----
Lightly tested (I am running it on my production BE, but there are many code paths untested, and there may be other uses that my semi-automated search and replaced missed).
fixes #372

Change offset to `offset` for MariaDB 10.6

---

mythtv/libs/libmythui/mythmainwindow.cpp
mythtv/libs/libmythui/mythmainwindow.h
mythtv/programs/mythfrontend/main.cpp
mythtv/programs/mythscreenwizard/main.cpp
mythtv/programs/mythtv-setup/main.cpp

@kmdewaal Same changes as https://github.com/MythTV/mythtv/pull/369
Rebased onto master and now in a different branch.  Should be able to fast-forward merge.
I tried to fix the diff/patch to show what I wanted.  First I tried editing the patch hunks, but since the changes were identical, git just used its version.  I tried adding the split hunks separately to change the patch output, but that didn't work either.
So I split that commit in two, adding the logging separately, which did show it how I want.  Unfortunately, github doesn't seem to care in its overall changes.

Merge ReinitDone into Init

---

mythtv/libs/libmyth/mythmediamonitor.cpp
mythtv/libs/libmythbase/mythsystemlegacy.cpp
mythtv/programs/mythfrontend/main.cpp
mythtv/settings.pro

Originally part of https://github.com/MythTV/mythtv/pull/442
Note: libmythupnp/httprequest.cpp changes were removed, since https://github.com/MythTV/mythtv/pull/448 deletes that code.

replace CONFIG_CYGWIN with Q_OS_WIN

---

mythtv/programs/mythwelcome/welcomesettings.h

cherry-picked from https://github.com/MythTV/mythtv/pull/438

mythwelcome/welcomesettings.h: remove errant MPUBLIC

---

mythtv/libs/libmyth/audio/audiooutputalsa.cpp
mythtv/libs/libmyth/audio/audiooutputaudiotrack.cpp
mythtv/libs/libmyth/audio/audiooutputca.cpp
mythtv/libs/libmyth/audio/audiooutputdigitalencoder.cpp
mythtv/libs/libmyth/audio/audiooutputnull.cpp
mythtv/libs/libmyth/audio/audiooutputoss.cpp
mythtv/libs/libmyth/audio/audiooutputsettings.h
mythtv/libs/libmyth/audio/spdifencoder.cpp
mythtv/libs/libmyth/mediamonitor-unix.h
mythtv/libs/libmyth/mythcontext.cpp
mythtv/libs/libmythtv/Bluray/mythbdbuffer.cpp
mythtv/libs/libmythtv/Bluray/mythbdbuffer.h
mythtv/libs/libmythtv/mythdeinterlacer.cpp
mythtv/libs/libmythui/devices/jsmenu.cpp
mythtv/libs/libmythui/mythpaintergpu.cpp
mythtv/libs/libmythui/opengl/mythpainteropengl.cpp
mythtv/libs/libmythui/platforms/drm/mythdrmhdr.cpp
mythtv/libs/libmythui/platforms/drm/mythdrmhdr.h
mythtv/libs/libmythui/platforms/mythdisplayosx.cpp
mythtv/libs/libmythui/platforms/mythdisplayx11.cpp
mythtv/programs/mythbackend/services/myth.cpp
mythtv/programs/mythbackend/servicesv2/v2myth.cpp
mythtv/programs/mythfrontend/exitprompt.cpp
mythtv/programs/mythfrontend/statusbox.cpp
mythtv/programs/mythtranscode/mpeg2fix.cpp
mythtv/programs/mythtranscode/mpeg2fix.h

Most inclusions were unnecessary.

replace config.h with mythconfig.h

---

mythplugins/mythweather/i18n/mythweather_de.ts
mythtv/i18n/mythfrontend_de.ts

Some missing parts of template translations and small consistency improvements in MythWeather and MythFrontend.

Translation: German fixes and improvements

---

mythtv/libs/libmythtv/mpeg/dvbdescriptors.cpp

Policical -> Political, capitalise words.

dvb-si: Fix typos in content descriptors

---

mythtv/libs/libmythbase/compat.h

Originally part of https://github.com/MythTV/mythtv/pull/442
Redone and now depends on https://github.com/MythTV/mythtv/pull/460 (change cherry-picked).

Rearranging compat.h

---

mythtv/libs/libmythbase/mythdate.cpp

Fixes [PR535](https://github.com/MythTV/mythtv/issues/535) on master

Master: Add missing include <array> to mythdate

---

mythtv/libs/libmyth/audio/audiooutputbase.cpp

- [ x] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [ x] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [ x] code compiles successfully without errors
- [x ] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [ x] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

Potential memory corruption problems in audiooutputbase

---

mythtv/libs/libmythbase/libmythbase.pro
mythtv/libs/libmythbase/mythdate.h
mythtv/libs/libmythbase/stringutil.cpp
mythtv/libs/libmythbase/stringutil.h
mythtv/libs/libmythbase/ternarycompare.h
mythtv/libs/libmythmetadata/dbaccess.cpp
mythtv/libs/libmythmetadata/videometadata.cpp
mythtv/programs/mythfrontend/editvideometadata.cpp
mythtv/programs/mythfrontend/prevreclist.cpp
mythtv/programs/mythfrontend/programrecpriority.cpp
mythtv/programs/mythfrontend/videofilter.cpp
mythtv/programs/mythfrontend/videolist.cpp

Was part of https://github.com/MythTV/mythtv/pull/438 .

rewrite sorting for clarity

---

mythtv/libs/libmyth/libmyth.pro

Originally part of https://github.com/MythTV/mythtv/pull/455

libmyth.pro: remove unused conditional HEADER

---

mythtv/programs/mythlcdserver/lcdprocclient.cpp

Fix #579 LCD time by replacing colon with space.

---

mythtv/configure
mythtv/libs/libmythfreemheg/BaseClasses.h
mythtv/libs/libmythfreemheg/ParseBinary.cpp
mythtv/libs/libmythfreemheg/ParseText.cpp
mythtv/libs/libmythfreemheg/ParseText.h
mythtv/libs/libmythfreemheg/Programs.cpp

Originally part of https://github.com/MythTV/mythtv/pull/455

libmythfreemheg cleanup

---

.github/workflows/buildfixes32.yml

Add Ubuntu 22.04 and replace deprecated macOS 10.15 with macOS 12.
Replaces https://github.com/MythTV/mythtv/pull/613

update GitHub Actions OS versions (fixes/32)

---

mythtv/configure
mythtv/libs/libmythfreemheg/BaseClasses.h
mythtv/libs/libmythfreemheg/ParseBinary.cpp
mythtv/libs/libmythfreemheg/ParseText.cpp
mythtv/libs/libmythfreemheg/ParseText.h
mythtv/libs/libmythfreemheg/Programs.cpp

@linuxdude42 This is a backport of https://github.com/MythTV/mythtv/pull/564 .  John Pilkington confirmed the FormatDate bug on the dev mailing list.
The first two commits applied cleanly, but are not strictly necessary.  I can remove them if you want.

fixes/32 fix MHEG FormatDate

---

.github/workflows/buildmaster.yml

The cache has not been working for some time, hopefully this will fix it.

GitHub Actions: update cache Action to v3

---

mythtv/libs/libmythupnp/upnphelpers.cpp

Update upnphelpers.cpp https://github.com/MythTV/mythtv/issues/687 

---

mythplugins/mythmusic/i18n/mythmusic_de.ts
mythtv/i18n/mythfrontend_de.ts

- [ x] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [ x] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [x ] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

Update german translation for v33 release

---

mythtv/bindings/python/MythTV/utility/dt.py

Since python 3.9, support for time-zones (1) is included in the standard installation.
Use this module in favor of the hand-crafted implementation of `MythTV.datetime.posixinfo()`
(1) https://docs.python.org/3/library/zoneinfo.html
Fixes MythTV#675

Python Bindings: Improve time-zone support

---

mythplugins/mythmusic/mythmusic/musiccommon.cpp
mythplugins/mythmusic/mythmusic/visualize.cpp
mythplugins/mythmusic/mythmusic/visualize.h
mythplugins/mythmusic/mythmusic/visualizerview.cpp

No functional change.  Trying to eliminate clang-tidy warnings from buildbot.

MythMusic: try to remove clang-tidy warnings

---

mythplugins/mythmusic/i18n/mythmusic_de.ts
mythtv/i18n/mythfrontend_de.ts

Update German translations for v34

---

mythplugins/mythmusic/i18n/mythmusic_it.ts
mythtv/i18n/mythfrontend_it.ts

Italian translation updated

---

mythtv/i18n/mythfrontend_de.ts

Translate newly added string

---

mythtv/i18n/mythbrowser_it.ts

While checking the Italian translation status I found three new sentences from my last update from yesterday so I released a new one

Updated italian translation

---

mythtv/i18n/mythfrontend_pl.ts

This is .pl community update to recent mythfrontend .pl translations updates.
Pls pull.
(it will be great also to backport this pull to fixes/34)
Thx in advance!

mythfrontend: translations: .pl: community updates

---

mythtv/libs/libmythui/platforms/mythscreensaverdbus.cpp

Remove relinquishing of the D-Bus sleep inhibition token upon reset.

---

mythtv/libs/libmythtv/channelscan/channelscan_sm.cpp

MPTS channel creation can be selected at the channel scan; if selected then one additional channel is created per transport stream which can be used to make recordings of the complete transport stream. An MPTS channel is created as a copy of an existing channel in the same transport stream. It did however happen that during the post processing the MPTS channel was discarded because of the "Logical Channel Numbers Required" or the "Complete Scan Data Required" options when the existing channel did not meet these criteria. This is now fixed by selecting an existing channel that has "Complete Scan Data", i.e. it does appear in PAT and PMT, and by setting a value for the logical channel number.

Fix MPTS channel creation

---

mythtv/programs/mythbackend/test/test_recordingextender/data/.gitattributes

Found with
`git grep -i rtsp -- ':!*/external/*'`

Add .gitattributes file

---

mythtv/libs/libmythtv/HLS/m3u.cpp
mythtv/libs/libmythtv/recorders/HLS/HLSReader.cpp
mythtv/libs/libmythtv/recorders/HLS/HLSReader.h
mythtv/libs/libmythtv/recorders/HLS/HLSStream.h

Slightly longer distance to live to accommodate varying IPTV throughput. Improved log messages and improved comment in the code.
Refs #936

IPTV HLS fixes

---

mythtv/libs/libmythtv/programdata.cpp

denullify the showtype, colorcode, title_pronounce, and inetref columns

---

mythtv/configure

Supports both jack's and pipewire's implementations

Modernize jack configure tests using pkgconf

---

mythplugins/mytharchive/i18n/mytharchive_de.ts
mythtv/i18n/mythfrontend_de.ts

Update German translations for v35

---

mythtv/docs/doxygen-create-developer-docs.cfg

See commit messages for justification.

Update EXCLUDE_PATTERNS in the doxyfile

---

.github/workflows/build-mythtv.yml

GitHub Actions: fix macOS runners / retire macOS 13 runner
